/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.com.cebycam.vistas.Administrador;

import ec.com.cebycam.accesodatos.Conexion;
import ec.com.cebycam.vistas.frmCambiarClave;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author lufeb
 */
public final class frmAdministradorMedico extends javax.swing.JFrame {
    public static String cedula=null;
    public static int codigo;
    public static String categoria;
    
    /** Creates new form frmInsertarMedico */
    public frmAdministradorMedico() {
        initComponents();
        frmAdministradorMedico.txtNombreUsuario.setText(cedula);
        frmAdministradorMedico.txtCodigoAdmin.setText(String.valueOf(codigo));
        frmAdministradorMedico.txtCategoria.setText(String.valueOf(categoria));
        
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(frmAdministradorMedico.DO_NOTHING_ON_CLOSE);
        JRootPane boton = SwingUtilities.getRootPane(btnRegAceptar); 
        boton.setDefaultButton(btnRegAceptar);
        txtRegNombreApellido.setCaretPosition(0);
        txtRegDireccion.setCaretPosition(0);
        txtRegCorreo.setCaretPosition(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRegNombreApellido = new javax.swing.JTextField();
        txtRegCedula = new javax.swing.JTextField();
        txtRegTelefono = new javax.swing.JTextField();
        cmbEspecialidades = new javax.swing.JComboBox<>();
        btnRegAceptar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtRegDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pwdRegContraseña = new javax.swing.JPasswordField();
        cmbRegSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtRegCorreo = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCodigoAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwdConfirmContraseña = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        pwdPalabraSecreta = new javax.swing.JPasswordField();
        txtCategoria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jpcFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        menuNuevoEnfermeria = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        editarMedico = new javax.swing.JMenuItem();
        MenuModEnfermeria = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        jmenuVerPersonal = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        jmenuBaja = new javax.swing.JMenuItem();
        jmenuEliminarEnfermera = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();
        barManual = new javax.swing.JMenuItem();
        cambiarClave = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Nuevo Médico");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setPreferredSize(new java.awt.Dimension(300, 230));

        jLabel3.setText("Nombre y Apellido");

        jLabel4.setText("Cédula");

        jLabel5.setText("Teléfono");

        jLabel6.setText("Sexo");

        jLabel7.setText("Especialidad");

        txtRegNombreApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRegNombreApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegNombreApellidoFocusLost(evt);
            }
        });
        txtRegNombreApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegNombreApellidoKeyTyped(evt);
            }
        });

        txtRegCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegCedulaKeyTyped(evt);
            }
        });

        txtRegTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegTelefonoKeyTyped(evt);
            }
        });

        cmbEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidades", "Medicina General", "Traumatología", "Ginecología", "Pediatría", "Medicina Interna", "Radiología", "Endocrinología", "Cirugía General", "Terapia Intensiva", "Cirugía Plástica", "Urología", "Otros" }));

        btnRegAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnRegAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegAceptarActionPerformed(evt);
            }
        });

        jLabel10.setText("Dirección");

        txtRegDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRegDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegDireccionFocusLost(evt);
            }
        });

        jLabel12.setText("Contraseña");

        cmbRegSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino" }));

        jLabel1.setText("Correo");

        txtRegCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRegCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegCorreoFocusLost(evt);
            }
        });

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigoAdmin.setEditable(false);
        txtCodigoAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bienvenido");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");

        jLabel8.setText("Rep. Contraseña");

        jLabel11.setText("ID Recuperación");

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Fecha de Inicio");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRegNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(32, 32, 32)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbRegSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(cmbEspecialidades, 0, 151, Short.MAX_VALUE)
                                            .addComponent(pwdRegContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(jpcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(20, 20, 20)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11))
                                .addGap(24, 24, 24)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRegDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRegTelefono)
                                    .addComponent(txtRegCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pwdConfirmContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(pwdPalabraSecreta)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(txtNombreUsuario))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(txtCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(144, 144, 144))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnRegAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtRegCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(txtRegTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(txtRegCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbRegSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(pwdPalabraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pwdConfirmContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(pwdRegContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jpcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnRegAceptar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/insertar_256px-0.png"))); // NOI18N
        menuInicio.setText("Inicio");

        menuNuevoEnfermeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/enfemera.png"))); // NOI18N
        menuNuevoEnfermeria.setText("Enfermería");
        menuNuevoEnfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoEnfermeriaActionPerformed(evt);
            }
        });
        menuInicio.add(menuNuevoEnfermeria);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/salir_256px-0.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        menuInicio.add(salir);

        jMenuBar1.add(menuInicio);

        menuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/editar_256px-0.png"))); // NOI18N
        menuEditar.setText("Editar");

        editarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/atencion-0.png"))); // NOI18N
        editarMedico.setText("Médico");
        editarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMedicoActionPerformed(evt);
            }
        });
        menuEditar.add(editarMedico);

        MenuModEnfermeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/enfemera.png"))); // NOI18N
        MenuModEnfermeria.setText("Enfermería");
        MenuModEnfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuModEnfermeriaActionPerformed(evt);
            }
        });
        menuEditar.add(MenuModEnfermeria);

        jMenuBar1.add(menuEditar);

        menuVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/ver.png"))); // NOI18N
        menuVer.setText("Ver");

        jmenuVerPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/personal.png"))); // NOI18N
        jmenuVerPersonal.setText("Historial Personal");
        jmenuVerPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuVerPersonalActionPerformed(evt);
            }
        });
        menuVer.add(jmenuVerPersonal);

        jMenuBar1.add(menuVer);

        menuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/tool.png"))); // NOI18N
        menuHistorial.setText("Herramientas");

        jmenuBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/atencion-0.png"))); // NOI18N
        jmenuBaja.setText("Deshabilitar Médico");
        jmenuBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuBajaActionPerformed(evt);
            }
        });
        menuHistorial.add(jmenuBaja);

        jmenuEliminarEnfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/enfemera.png"))); // NOI18N
        jmenuEliminarEnfermera.setText("Deshabilitar Enfermería");
        jmenuEliminarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuEliminarEnfermeraActionPerformed(evt);
            }
        });
        menuHistorial.add(jmenuEliminarEnfermera);

        jMenuBar1.add(menuHistorial);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/ayuda-0.png"))); // NOI18N
        menuAyuda.setText("Ayuda");

        acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/acerca_de_256px-0.png"))); // NOI18N
        acerca.setText("Acerca de");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        menuAyuda.add(acerca);

        barManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/listar_256px-0.png"))); // NOI18N
        barManual.setText("Manual de Usuario");
        barManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barManualActionPerformed(evt);
            }
        });
        menuAyuda.add(barManual);

        cambiarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/clave_256px-0.png"))); // NOI18N
        cambiarClave.setText("Cambiar clave");
        cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClaveActionPerformed(evt);
            }
        });
        menuAyuda.add(cambiarClave);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegAceptarActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        String clave1=String.valueOf(pwdRegContraseña.getPassword());
        String clave2=String.valueOf(pwdConfirmContraseña.getPassword());
        String recuperacion=String.valueOf(pwdPalabraSecreta.getPassword());
        
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(txtRegNombreApellido.getText().equals("")||txtRegCedula.getText().equals("")||txtRegTelefono.getText().equals("")||txtRegDireccion.getText().equals("")||
                    txtRegCorreo.getText().equals("")||cmbRegSexo.getSelectedItem().toString().equals("Seleccione")
                    ||cmbEspecialidades.getSelectedItem().toString().equals("Especialidades")||clave1.equals("")||clave2.equals("")||clave1.equals("")||recuperacion.equals("")){
                JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                if(Arrays.equals(pwdRegContraseña.getPassword(), pwdConfirmContraseña.getPassword())){
                    try{
                        String sql="select insertarMedico(?,?,?,?,?,?,?,?,?,?,?);";

                        try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                            ps.setString(1, txtRegNombreApellido.getText());
                            ps.setString(2, cmbEspecialidades.getSelectedItem().toString());
                            ps.setString(3, txtRegDireccion.getText());
                            ps.setString(4, txtRegTelefono.getText());
                            ps.setString(5, txtRegCedula.getText());
                            ps.setString(6, cmbRegSexo.getSelectedItem().toString());
                            ps.setString(7, String.valueOf(pwdRegContraseña.getPassword()));
                            ps.setString(8, txtRegCorreo.getText());
                            ps.setInt(9, Integer.parseInt(txtCodigoAdmin.getText()));
                            ps.setString(10, String.valueOf(pwdPalabraSecreta.getPassword()));
                            ps.setDate(11, new java.sql.Date(jpcFechaInicio.getDate().getTime()));
                            ps.execute();
                            ps.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        txtRegNombreApellido.setText("");
                        cmbEspecialidades.setSelectedItem("Especialidades");
                        txtRegDireccion.setText("");
                        txtRegTelefono.setText("");
                        txtRegCedula.setText("");
                        cmbRegSexo.setSelectedItem("Seleccione");
                        pwdRegContraseña.setText("");
                        pwdConfirmContraseña.setText("");
                        txtRegCorreo.setText("");
                        pwdPalabraSecreta.setText("");
                        jpcFechaInicio.setDate(null);
                        
                        JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
                    }catch(SQLException | NumberFormatException | HeadlessException x){
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                    }finally {
                        con.desconectar();
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Las claves no concuerdan", "CEBYCAM-CES",
                        JOptionPane.ERROR_MESSAGE);
                    pwdRegContraseña.setText("");
                    pwdConfirmContraseña.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnRegAceptarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        cerrar();
    }//GEN-LAST:event_salirActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema médico CEBYCAM-CES. Versión 2.5\nCopyright (C). 2019. UNACH-VINCULACIÓN\n        Todos los Derechos Reservados", "CEBYCAM-CES",
                JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_acercaActionPerformed

    private void cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClaveActionPerformed
        JOptionPane.showMessageDialog(this, "Recuerde, el sistema se cerrará \n    luego de cambiar la clave!",
                                "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        frmCambiarClave frm = new frmCambiarClave();
        frm.setVisible(true);
    }//GEN-LAST:event_cambiarClaveActionPerformed

    private void editarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMedicoActionPerformed
        frmModificarMedico frm = null;
        try {
            frm = new frmModificarMedico();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        frm.setVisible(true);
    }//GEN-LAST:event_editarMedicoActionPerformed
    
    public void cerrar(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "CEBYCAM-CES", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    public void abrirarchivo(String archivo){
         try {
            File objetofile = new File (archivo);
            Desktop.getDesktop().open(objetofile);
         }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error "+ex,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
         }
    } 
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void txtRegNombreApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegNombreApellidoFocusGained
        txtRegNombreApellido.setCaretPosition(0);
    }//GEN-LAST:event_txtRegNombreApellidoFocusGained

    private void txtRegDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegDireccionFocusGained
        txtRegDireccion.setCaretPosition(0);
    }//GEN-LAST:event_txtRegDireccionFocusGained

    private void txtRegCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegCorreoFocusGained
        txtRegCorreo.setCaretPosition(0);
    }//GEN-LAST:event_txtRegCorreoFocusGained

    private void txtRegNombreApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegNombreApellidoFocusLost
        txtRegNombreApellido.setCaretPosition(0);
    }//GEN-LAST:event_txtRegNombreApellidoFocusLost

    private void txtRegDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegDireccionFocusLost
        txtRegDireccion.setCaretPosition(0);
    }//GEN-LAST:event_txtRegDireccionFocusLost

    private void txtRegCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegCorreoFocusLost
        txtRegCorreo.setCaretPosition(0);
    }//GEN-LAST:event_txtRegCorreoFocusLost

    private void menuNuevoEnfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoEnfermeriaActionPerformed
        frmInsertarEnfemera enfermera = new frmInsertarEnfemera();
        enfermera.setVisible(true);
    }//GEN-LAST:event_menuNuevoEnfermeriaActionPerformed

    private void MenuModEnfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuModEnfermeriaActionPerformed
        frmModificarEnfermera enfermera = null;
        try {
            enfermera = new frmModificarEnfermera();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        enfermera.setVisible(true);
    }//GEN-LAST:event_MenuModEnfermeriaActionPerformed

    private void txtRegCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegCedulaKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtRegCedula.getText().length() == 10)  
             evt.consume();
    }//GEN-LAST:event_txtRegCedulaKeyTyped

    private void txtRegTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegTelefonoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtRegTelefono.getText().length() == 10)  
             evt.consume();
    }//GEN-LAST:event_txtRegTelefonoKeyTyped

    private void txtRegNombreApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNombreApellidoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b!=0){
            evt.consume();
        }
    }//GEN-LAST:event_txtRegNombreApellidoKeyTyped

    private void barManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barManualActionPerformed
        abrirarchivo("manual.chm");
    }//GEN-LAST:event_barManualActionPerformed

    private void jmenuBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuBajaActionPerformed
        frmEliminarMedico del = null;
        try {
            del = new frmEliminarMedico();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        del.setVisible(true);
    }//GEN-LAST:event_jmenuBajaActionPerformed

    private void jmenuEliminarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuEliminarEnfermeraActionPerformed
        frmEliminarEnfermeria del = null;
        try {
            del = new frmEliminarEnfermeria();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        del.setVisible(true);
    }//GEN-LAST:event_jmenuEliminarEnfermeraActionPerformed

    private void jmenuVerPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuVerPersonalActionPerformed
        frmPersonalBaja prev = null;
        try {
            prev = new frmPersonalBaja();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmAdministradorMedico.class.getName()).log(Level.SEVERE, null, ex);
        }
        prev.setVisible(true);
    }//GEN-LAST:event_jmenuVerPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmAdministrador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuModEnfermeria;
    private javax.swing.JMenuItem acerca;
    private javax.swing.JMenuItem barManual;
    private javax.swing.JButton btnRegAceptar;
    private javax.swing.JMenuItem cambiarClave;
    public static javax.swing.JComboBox<String> cmbEspecialidades;
    public static javax.swing.JComboBox<String> cmbRegSexo;
    private javax.swing.JMenuItem editarMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JMenuItem jmenuBaja;
    private javax.swing.JMenuItem jmenuEliminarEnfermera;
    private javax.swing.JMenuItem jmenuVerPersonal;
    private org.jdesktop.swingx.JXDatePicker jpcFechaInicio;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenuItem menuNuevoEnfermeria;
    private javax.swing.JMenu menuVer;
    private javax.swing.JPanel panel1;
    private javax.swing.JPasswordField pwdConfirmContraseña;
    private javax.swing.JPasswordField pwdPalabraSecreta;
    public static javax.swing.JPasswordField pwdRegContraseña;
    private javax.swing.JMenuItem salir;
    public static javax.swing.JTextField txtCategoria;
    public static javax.swing.JTextField txtCodigoAdmin;
    public static javax.swing.JTextField txtNombreUsuario;
    public static javax.swing.JTextField txtRegCedula;
    public static javax.swing.JTextField txtRegCorreo;
    public static javax.swing.JTextField txtRegDireccion;
    public static javax.swing.JTextField txtRegNombreApellido;
    public static javax.swing.JTextField txtRegTelefono;
    // End of variables declaration//GEN-END:variables

}
