/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.com.cebycam.vistas.Administrador;

import ec.com.cebycam.accesodatos.Conexion;
import ec.com.cebycam.vistas.frmCambiarClave;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lufeb
 */
public final class frmAdministradorEmpleado extends javax.swing.JFrame {
    public static String cedula=null;
    public static int codigo;
    public static String categoria;
    DefaultTableModel modelo;
    TableRowSorter trsFiltro;
    
    /** Creates new form frmInsertarMedico
     * @throws java.sql.SQLException
     * @throws java.io.IOException */
    public frmAdministradorEmpleado() throws SQLException, IOException {
        initComponents();
        frmAdministradorEmpleado.txtNombreUsuario.setText(cedula);
        frmAdministradorEmpleado.txtCodigoAdmin.setText(String.valueOf(codigo));
        frmAdministradorEmpleado.txtCategoria.setText(String.valueOf(categoria));
        consultar_tipoEmpleado();
        cargarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(frmAdministradorEmpleado.DO_NOTHING_ON_CLOSE);
        JRootPane boton = SwingUtilities.getRootPane(btnRegEmpleado); 
        boton.setDefaultButton(btnRegEmpleado);
        txtRegNombre.setCaretPosition(0);
        txtRegDireccion.setCaretPosition(0);
        txtRegCorreo.setCaretPosition(0);
        
        
        txtCredUsuario.setEnabled(false);
        pwdCredContraseña.setEnabled(false);
        jpcCredFechaInicio.setEnabled(false);
        txtCredCodEmpleado.setEnabled(false);
        tablaEmpleados.setEnabled(false);
        pwdCredPalabraSecreta.setEnabled(false);
        pwdCredConfirmContraseña.setEnabled(false);
        jpcCredFechaFin.setEnabled(false);
        btnRegCredencial.setEnabled(false);
        btnActualizarCredencial.setEnabled(false);
        cmbFiltroEmpleado.setEnabled(false);
        txtBusquedaEmpleado.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRegNombre = new javax.swing.JTextField();
        txtRegCedula = new javax.swing.JTextField();
        txtRegTelefono = new javax.swing.JTextField();
        cmbEspecialidades = new javax.swing.JComboBox<>();
        btnRegEmpleado = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtRegDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pwdCredContraseña = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        txtRegCorreo = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCodigoAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwdCredConfirmContraseña = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        pwdCredPalabraSecreta = new javax.swing.JPasswordField();
        txtCategoria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jpcCredFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        txtRegApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCredUsuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jpcCredFechaFin = new org.jdesktop.swingx.JXDatePicker();
        Tipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        txtCodCategoria = new javax.swing.JTextField();
        btnRegCredencial = new javax.swing.JButton();
        Tipo1 = new javax.swing.JLabel();
        txtCredCodEmpleado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtBusquedaEmpleado = new javax.swing.JTextField();
        btnActualizarCredencial = new javax.swing.JButton();
        cmbFiltroEmpleado = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        editarMedico = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        jmenuVerPersonal = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        jmenuBaja = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();
        barManual = new javax.swing.JMenuItem();
        cambiarClave = new javax.swing.JMenuItem();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Nuevo Médico");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setPreferredSize(new java.awt.Dimension(300, 230));

        jLabel3.setText("Nombre:");

        jLabel4.setText("Cédula:");

        jLabel5.setText("Teléfono:");

        jLabel7.setText("Título:");

        txtRegNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRegNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegNombreFocusLost(evt);
            }
        });
        txtRegNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegNombreKeyTyped(evt);
            }
        });

        txtRegCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegCedulaActionPerformed(evt);
            }
        });
        txtRegCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegCedulaKeyTyped(evt);
            }
        });

        txtRegTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRegTelefonoKeyTyped(evt);
            }
        });

        cmbEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especialidades", "Medicina General", "Traumatología", "Ginecología", "Pediatría", "Medicina Interna", "Radiología", "Endocrinología", "Cirugía General", "Terapia Intensiva", "Cirugía Plástica", "Urología", "Otros" }));

        btnRegEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnRegEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegEmpleadoActionPerformed(evt);
            }
        });

        jLabel10.setText("Dirección:");

        txtRegDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRegDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegDireccionFocusLost(evt);
            }
        });

        jLabel12.setText("Contraseña:");

        jLabel1.setText("Correo:");

        txtRegCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRegCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegCorreoFocusLost(evt);
            }
        });

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigoAdmin.setEditable(false);
        txtCodigoAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");

        jLabel8.setText("Rep. Contraseña:");

        jLabel11.setText("ID Recuperación:");

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setText("Fecha Inicio:");

        jLabel6.setText("Apellido:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("CREDENCIALES");

        jLabel15.setText("Usuario:");

        jLabel16.setText("Fecha Finalización:");

        Tipo.setText("Tipo");

        cmbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoItemStateChanged(evt);
            }
        });

        txtCodCategoria.setEditable(false);
        txtCodCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnRegCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnRegCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCredencialActionPerformed(evt);
            }
        });

        Tipo1.setText("Empleado");

        txtCredCodEmpleado.setEditable(false);
        txtCredCodEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Empleados"));

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleados);

        jLabel17.setText("Búsqueda");

        txtBusquedaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaEmpleadoKeyTyped(evt);
            }
        });

        btnActualizarCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnActualizarCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCredencialActionPerformed(evt);
            }
        });

        cmbFiltroEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Código", "Nombre" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbFiltroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusquedaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizarCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbFiltroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusquedaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnActualizarCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtRegDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(71, 71, 71)
                                        .addComponent(txtRegCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(67, 67, 67)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRegApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(Tipo))
                                .addGap(31, 31, 31)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRegTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRegCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEspecialidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(359, 359, 359)
                                .addComponent(btnRegEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(253, 253, 253)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addComponent(txtCategoria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addComponent(btnRegCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(231, 231, 231))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel1Layout.createSequentialGroup()
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel15))
                                                .addGap(32, 32, 32)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCredCodEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pwdCredContraseña)
                                                    .addComponent(txtCredUsuario)
                                                    .addComponent(jpcCredFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(27, 27, 27)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel16))
                                                .addGap(18, 18, 18)
                                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(pwdCredConfirmContraseña)
                                                    .addComponent(pwdCredPalabraSecreta)
                                                    .addComponent(jpcCredFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(Tipo1))
                                        .addGap(18, 18, 18)))))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(txtRegCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(cmbEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(txtRegTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Tipo)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRegDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnRegEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(37, 37, 37)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(pwdCredPalabraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtCredUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(pwdCredContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(pwdCredConfirmContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jpcCredFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jpcCredFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tipo1)
                            .addComponent(txtCredCodEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegCredencial)
                        .addGap(36, 36, 36))))
        );

        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/insertar_256px-0.png"))); // NOI18N
        menuInicio.setText("Inicio");

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/salir_256px-0.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        menuInicio.add(salir);

        jMenuBar1.add(menuInicio);

        menuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/editar_256px-0.png"))); // NOI18N
        menuEditar.setText("Editar");

        editarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/atencion-0.png"))); // NOI18N
        editarMedico.setText("Empleado");
        editarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarMedicoActionPerformed(evt);
            }
        });
        menuEditar.add(editarMedico);

        jMenuBar1.add(menuEditar);

        menuVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/ver.png"))); // NOI18N
        menuVer.setText("Ver");

        jmenuVerPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/personal.png"))); // NOI18N
        jmenuVerPersonal.setText("Historial Personal");
        jmenuVerPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuVerPersonalActionPerformed(evt);
            }
        });
        menuVer.add(jmenuVerPersonal);

        jMenuBar1.add(menuVer);

        menuHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/tool.png"))); // NOI18N
        menuHistorial.setText("Herramientas");

        jmenuBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/atencion-0.png"))); // NOI18N
        jmenuBaja.setText("Deshabilitar Médico");
        jmenuBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuBajaActionPerformed(evt);
            }
        });
        menuHistorial.add(jmenuBaja);

        jMenuBar1.add(menuHistorial);

        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/ayuda-0.png"))); // NOI18N
        menuAyuda.setText("Ayuda");

        acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/acerca_de_256px-0.png"))); // NOI18N
        acerca.setText("Acerca de");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        menuAyuda.add(acerca);

        barManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/listar_256px-0.png"))); // NOI18N
        barManual.setText("Manual de Usuario");
        barManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barManualActionPerformed(evt);
            }
        });
        menuAyuda.add(barManual);

        cambiarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/clave_256px-0.png"))); // NOI18N
        cambiarClave.setText("Cambiar clave");
        cambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarClaveActionPerformed(evt);
            }
        });
        menuAyuda.add(cambiarClave);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void consultar_tipoEmpleado() throws SQLException, IOException{
        Conexion con= new Conexion();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT tipo FROM public.categoriaempleado order by tipo asc";
        try {
           pst=con.conectar().prepareStatement(sql);
           rs = pst.executeQuery();
           cmbTipo.addItem("Seleccione una opción");
           while(rs.next()){
               cmbTipo.addItem(rs.getString("tipo"));
           }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos",
                    "CEBYCAM-CES", JOptionPane.ERROR_MESSAGE);
        }finally{
            con.desconectar();
            rs.close();
        }
    }
    
    public void cargarTabla() throws SQLException, IOException{
        Conexion con = new Conexion();
        con.conectar();
        ResultSet rs = null;
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        
        try{
            rs = con.ejecutarQuery("SELECT idempleado, nombre FROM public.empleado ORDER BY nombre ASC;");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
            rs.close();
        }
        tablaEmpleados.setModel(modelo);
        modelo.fireTableDataChanged();
        
        
        tablaEmpleados.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaEmpleados.getColumnModel().getColumn(0).setMinWidth(0);
        tablaEmpleados.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    public void filtro() {
        int columnaABuscar = 0;
        if (cmbFiltroEmpleado.getSelectedItem().equals("Código")) {
            columnaABuscar = 0;
        }
        if (cmbFiltroEmpleado.getSelectedItem() == "Nombre") {
            columnaABuscar = 1;
        }
        String replace = txtBusquedaEmpleado.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tablaEmpleados.setRowSorter(trsFiltro);
    }
        
    private void btnRegEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegEmpleadoActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(txtRegNombre.getText().equals("")||txtRegCedula.getText().equals("")||txtRegTelefono.getText().equals("")||txtRegDireccion.getText().equals("")||
                    txtRegCorreo.getText().equals("")||txtRegApellido.getText().equals("")||txtCodCategoria.getText().equals("")
                    ||cmbEspecialidades.getSelectedItem().toString().equals("Especialidades")
                    ||cmbTipo.getSelectedItem().toString().equals("Seleccione una opción")){
                JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                    try{
                        String insertarCategoria="INSERT INTO public.empleado(\n" +
"	idcategoriaempleado, nombre, apellido, cedula, direccion, telefono, correo, titulo)\n" +
"	VALUES (?, ?, ?, ?, ?, ?, ?, ?);";
                        try (PreparedStatement ps = con.conectar().prepareStatement(insertarCategoria)) {
                            ps.setInt(1, Integer.parseInt(txtCodCategoria.getText()));
                            ps.setString(2, txtRegNombre.getText());
                            ps.setString(3, txtRegApellido.getText());
                            ps.setString(4, txtRegCedula.getText());
                            ps.setString(5, txtRegDireccion.getText());
                            ps.setString(6, txtRegTelefono.getText());
                            ps.setString(7, txtRegCorreo.getText());
                            ps.setString(8, cmbEspecialidades.getSelectedItem().toString());
                            
                            ps.execute();
                            ps.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }catch(SQLException | NumberFormatException | HeadlessException x){
                        JOptionPane.showMessageDialog(rootPane, "Error al guardar la información "+x);
                    }finally {
                        con.desconectar();
                    }
                    
                    txtRegNombre.setText("");
                    txtRegApellido.setText("");
                    txtRegCedula.setText("");
                    txtRegDireccion.setText("");
                    txtRegTelefono.setText("");
                    txtRegCorreo.setText("");
                    cmbEspecialidades.setSelectedItem("Especialidades");
                    cmbTipo.setSelectedItem("Seleccione una opción");
                    txtCodCategoria.setText("");
                    
                    JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
                    
                    txtCredUsuario.setEnabled(true);
                    pwdCredContraseña.setEnabled(true);
                    jpcCredFechaInicio.setEnabled(true);
                    txtCredCodEmpleado.setEnabled(true);
                    tablaEmpleados.setEnabled(true);
                    pwdCredPalabraSecreta.setEnabled(true);
                    pwdCredConfirmContraseña.setEnabled(true);
                    jpcCredFechaFin.setEnabled(true);
                    btnRegCredencial.setEnabled(true);
                    btnActualizarCredencial.setEnabled(true);
                    cmbFiltroEmpleado.setEnabled(true);
                    txtBusquedaEmpleado.setEnabled(true);
                }
        }
    }//GEN-LAST:event_btnRegEmpleadoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        cerrar();
    }//GEN-LAST:event_salirActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema médico CEBYCAM-CES. Versión 2.5\nCopyright (C). 2019. UNACH-VINCULACIÓN\n        Todos los Derechos Reservados", "CEBYCAM-CES",
                JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_acercaActionPerformed

    private void cambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarClaveActionPerformed
        JOptionPane.showMessageDialog(this, "Recuerde, el sistema se cerrará \n    luego de cambiar la clave!",
                                "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        frmCambiarClave frm = new frmCambiarClave();
        frm.setVisible(true);
    }//GEN-LAST:event_cambiarClaveActionPerformed

    private void editarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarMedicoActionPerformed
        frmModificarEmpleado frm = null;
        try {
            frm = new frmModificarEmpleado();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        frm.setVisible(true);
    }//GEN-LAST:event_editarMedicoActionPerformed
    
    public void cerrar(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "CEBYCAM-CES", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    public void abrirarchivo(String archivo){
         try {
            File objetofile = new File (archivo);
            Desktop.getDesktop().open(objetofile);
         }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error "+ex,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
         }
    } 
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void txtRegNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegNombreFocusGained
        txtRegNombre.setCaretPosition(0);
    }//GEN-LAST:event_txtRegNombreFocusGained

    private void txtRegDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegDireccionFocusGained
        txtRegDireccion.setCaretPosition(0);
    }//GEN-LAST:event_txtRegDireccionFocusGained

    private void txtRegCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegCorreoFocusGained
        txtRegCorreo.setCaretPosition(0);
    }//GEN-LAST:event_txtRegCorreoFocusGained

    private void txtRegNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegNombreFocusLost
        txtRegNombre.setCaretPosition(0);
    }//GEN-LAST:event_txtRegNombreFocusLost

    private void txtRegDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegDireccionFocusLost
        txtRegDireccion.setCaretPosition(0);
    }//GEN-LAST:event_txtRegDireccionFocusLost

    private void txtRegCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegCorreoFocusLost
        txtRegCorreo.setCaretPosition(0);
    }//GEN-LAST:event_txtRegCorreoFocusLost

    private void txtRegCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegCedulaKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtRegCedula.getText().length() == 10)  
             evt.consume();
    }//GEN-LAST:event_txtRegCedulaKeyTyped

    private void txtRegTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegTelefonoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtRegTelefono.getText().length() == 10)  
             evt.consume();
    }//GEN-LAST:event_txtRegTelefonoKeyTyped

    private void txtRegNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRegNombreKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b!=0){
            evt.consume();
        }
    }//GEN-LAST:event_txtRegNombreKeyTyped

    private void barManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barManualActionPerformed
        abrirarchivo("manual.chm");
    }//GEN-LAST:event_barManualActionPerformed

    private void jmenuBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuBajaActionPerformed
        frmEliminarEmpleado del = null;
        try {
            del = new frmEliminarEmpleado();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        del.setVisible(true);
    }//GEN-LAST:event_jmenuBajaActionPerformed

    private void jmenuVerPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuVerPersonalActionPerformed
        frmPersonalBaja prev = null;
        try {
            prev = new frmPersonalBaja();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        prev.setVisible(true);
    }//GEN-LAST:event_jmenuVerPersonalActionPerformed

    private void txtRegCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegCedulaActionPerformed

    private void cmbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoItemStateChanged
        Conexion con= new Conexion();
        String tipo = cmbTipo.getSelectedItem().toString();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT idcategoriaempleado FROM public.categoriaempleado where tipo='"+tipo+"'";
        try {
           pst=con.conectar().prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next()){
               txtCodCategoria.setText(rs.getString("idcategoriaempleado"));
           }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos",
                    "CEBYCAM-CES", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbTipoItemStateChanged

    private void btnRegCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCredencialActionPerformed
        String clave1=String.valueOf(pwdCredContraseña.getPassword());
        String clave2=String.valueOf(pwdCredConfirmContraseña.getPassword());
        String recuperacion=String.valueOf(pwdCredPalabraSecreta.getPassword());
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(txtCredUsuario.getText().equals("")||clave1.equals("")||jpcCredFechaInicio.getDate()==null||txtCredCodEmpleado.getText().equals("")
                    ||recuperacion.equals("")
                    ||clave2.equals("")||jpcCredFechaFin.getDate()==null){
                JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                if(Arrays.equals(pwdCredContraseña.getPassword(), pwdCredConfirmContraseña.getPassword())){
                    //usuario
                    try{
                        String insertarCategoria="INSERT INTO public.usuario(\n" +
"	idempleado, usuario, clave, recuperacion)\n" +
"	VALUES (?, ?, ?, ?);";
                        try (PreparedStatement ps = con.conectar().prepareStatement(insertarCategoria)) {
                            ps.setInt(1, Integer.parseInt(txtCredCodEmpleado.getText()));
                            ps.setString(2, txtCredUsuario.getText());
                            ps.setString(3, String.valueOf(pwdCredContraseña.getPassword()));
                            ps.setString(4, String.valueOf(pwdCredPalabraSecreta.getPassword()));
                            
                            ps.execute();
                            ps.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }catch(SQLException | NumberFormatException | HeadlessException x){
                        JOptionPane.showMessageDialog(rootPane, "Error al guardar la información "+x);
                    }finally {
                        con.desconectar();
                    }
                    //empleado
                    try{
                        String insertarCategoria="INSERT INTO public.contrato(\n" +
"	idempleado, fechainicio, fechafin)\n" +
"	VALUES (?, ?, ?);";
                        try (PreparedStatement ps = con.conectar().prepareStatement(insertarCategoria)) {
                            ps.setInt(1, Integer.parseInt(txtCredCodEmpleado.getText()));
                            ps.setDate(2, new java.sql.Date(jpcCredFechaInicio.getDate().getTime()));
                            ps.setDate(3, new java.sql.Date(jpcCredFechaFin.getDate().getTime()));
                            
                            ps.execute();
                            ps.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }catch(SQLException | NumberFormatException | HeadlessException x){
                        JOptionPane.showMessageDialog(rootPane, "Error al guardar la información "+x);
                    }finally {
                        con.desconectar();
                    }
                    
                    txtCredUsuario.setText("");
                    pwdCredContraseña.setText("");
                    pwdCredPalabraSecreta.setText("");
                    pwdCredConfirmContraseña.setText("");
                    jpcCredFechaInicio.setDate(null);
                    jpcCredFechaFin.setDate(null);
                    txtCredCodEmpleado.setText("");
                    JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
                }else{
                    JOptionPane.showMessageDialog(null,"Las claves no concuerdan", "CEBYCAM-CES",
                            JOptionPane.ERROR_MESSAGE);
                    pwdCredContraseña.setText("");
                    pwdCredConfirmContraseña.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnRegCredencialActionPerformed
   
    private void btnActualizarCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCredencialActionPerformed
        Conexion con = new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs = null;
        modelo.setRowCount( 0 );
        try{
            rs = con.ejecutarQuery("SELECT idempleado, nombre FROM public.empleado ORDER BY nombre ASC;");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmAdministradorEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+ex);
            }
        }
    }//GEN-LAST:event_btnActualizarCredencialActionPerformed

    private void tablaEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosMouseClicked
        int selectedRowIndex = tablaEmpleados.rowAtPoint(evt.getPoint());
        txtCredCodEmpleado.setText(tablaEmpleados.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_tablaEmpleadosMouseClicked

    private void txtBusquedaEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaEmpleadoKeyTyped
        txtBusquedaEmpleado.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusquedaEmpleado.getText());
                txtBusquedaEmpleado.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaEmpleados.getModel());
        tablaEmpleados.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaEmpleadoKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmAdministrador().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JMenuItem acerca;
    private javax.swing.JMenuItem barManual;
    private javax.swing.JButton btnActualizarCredencial;
    private javax.swing.JButton btnRegCredencial;
    private javax.swing.JButton btnRegEmpleado;
    private javax.swing.JMenuItem cambiarClave;
    public static javax.swing.JComboBox<String> cmbEspecialidades;
    private javax.swing.JComboBox<String> cmbFiltroEmpleado;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JMenuItem editarMedico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem jmenuBaja;
    private javax.swing.JMenuItem jmenuVerPersonal;
    private org.jdesktop.swingx.JXDatePicker jpcCredFechaFin;
    private org.jdesktop.swingx.JXDatePicker jpcCredFechaInicio;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuVer;
    private javax.swing.JPanel panel1;
    private javax.swing.JPasswordField pwdCredConfirmContraseña;
    public static javax.swing.JPasswordField pwdCredContraseña;
    private javax.swing.JPasswordField pwdCredPalabraSecreta;
    private javax.swing.JMenuItem salir;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTextField txtBusquedaEmpleado;
    public static javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodCategoria;
    public static javax.swing.JTextField txtCodigoAdmin;
    private javax.swing.JTextField txtCredCodEmpleado;
    private javax.swing.JTextField txtCredUsuario;
    public static javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtRegApellido;
    public static javax.swing.JTextField txtRegCedula;
    public static javax.swing.JTextField txtRegCorreo;
    public static javax.swing.JTextField txtRegDireccion;
    public static javax.swing.JTextField txtRegNombre;
    public static javax.swing.JTextField txtRegTelefono;
    // End of variables declaration//GEN-END:variables

}
