/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cebycam.vistas.Administrador;
import ec.com.cebycam.accesodatos.Conexion;
import java.awt.HeadlessException;
import java.awt.event.*;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author lufeb
 */
public final class frmEliminarEmpleado extends javax.swing.JFrame {
    DefaultTableModel modelo;
    TableRowSorter trsFiltro;
    /**
     * Creates new form frmModificarMedico
     * @throws java.io.IOException
     * @throws java.sql.SQLException
     */
    
    public frmEliminarEmpleado() throws IOException, SQLException {
        initComponents();
        cargarTabla();
        ordenarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        JRootPane boton = SwingUtilities.getRootPane(btnDelAceptar); 
        boton.setDefaultButton(btnDelAceptar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGrupoDelete = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleadosRegistrados = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cmbListar = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFechaInicio = new javax.swing.JTextField();
        btnDelAceptar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        rbtnSi = new javax.swing.JRadioButton();
        rbtnNo = new javax.swing.JRadioButton();
        txtFechaFin = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModNombre = new javax.swing.JTextField();
        txtModCedula = new javax.swing.JTextField();
        txtModTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtModDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtRegCorreo = new javax.swing.JTextField();
        txtModApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        txtCategoriaEmp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEspecialidades = new javax.swing.JTextField();

        rbtnGrupoDelete.add(rbtnSi);
        rbtnGrupoDelete.add(rbtnNo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Deshabilitar Médico");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados Registrados"));
        jPanel1.setToolTipText("");

        tablaEmpleadosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleadosRegistrados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaEmpleadosRegistrados.setAutoscrolls(false);
        tablaEmpleadosRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosRegistradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleadosRegistrados);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel16.setText("Buscar por:");

        cmbListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Código", "Nombre", "Cédula" }));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBusqueda)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cmbListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Información"));

        jLabel2.setText("Fecha de inicio:");

        jLabel8.setText("Fecha de culminación:");

        txtFechaInicio.setEditable(false);

        btnDelAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnDelAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelAceptarActionPerformed(evt);
            }
        });

        jLabel11.setText("Activo:");

        rbtnSi.setText("Si");

        rbtnNo.setText("No");

        txtFechaFin.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rbtnSi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(rbtnNo))
                    .addComponent(txtFechaInicio)
                    .addComponent(txtFechaFin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbtnSi)
                    .addComponent(rbtnNo))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelAceptar)
                        .addGap(35, 35, 35))))
        );

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setPreferredSize(new java.awt.Dimension(300, 230));

        jLabel3.setText("Nombre:");

        jLabel4.setText("Cédula:");

        jLabel5.setText("Teléfono:");

        jLabel7.setText("Título:");

        txtModNombre.setEditable(false);
        txtModNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModNombreFocusLost(evt);
            }
        });

        txtModCedula.setEditable(false);

        txtModTelefono.setEditable(false);

        jLabel10.setText("Dirección:");

        txtModDireccion.setEditable(false);
        txtModDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModDireccionFocusLost(evt);
            }
        });

        jLabel1.setText("Correo:");

        txtRegCorreo.setEditable(false);
        txtRegCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRegCorreoFocusLost(evt);
            }
        });

        txtModApellido.setEditable(false);
        txtModApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModApellidoFocusLost(evt);
            }
        });

        jLabel6.setText("Apellido:");

        Tipo.setText("Categoria:");

        txtCategoriaEmp.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("EMPLEADO");

        txtCodigoEmpleado.setEditable(false);
        txtCodigoEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setText("Código");

        txtEspecialidades.setEditable(false);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addGap(38, 38, 38)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tipo)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCategoriaEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtModTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(txtRegCorreo)
                            .addComponent(txtEspecialidades))))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtModTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtRegCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtEspecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCategoriaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tipo))
                                .addGap(18, 18, 18)
                                .addComponent(txtModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelAceptarActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmEliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(txtCodigoEmpleado.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                  try{
                      String sql="UPDATE public.usuario\n" +
"	SET estado=?\n" +
"	WHERE idempleado=?;";
                    try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                        if(rbtnSi.isSelected()){
                            ps.setString(1, "activo");
                        }else{
                            if(rbtnNo.isSelected()){
                                ps.setString(1, "deshabilitado");
                            }
                        }
                        ps.setInt(2, Integer.parseInt(txtCodigoEmpleado.getText()));
                        ps.execute();
                        ps.close();
                    } catch (IOException ex) {
                        Logger.getLogger(frmEliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtCodigoEmpleado.setText("");
                    txtModNombre.setText("");
                    txtModApellido.setText("");
                    txtModCedula.setText("");
                    txtModDireccion.setText("");
                    txtModTelefono.setText("");
                    txtRegCorreo.setText("");
                    txtEspecialidades.setText("");
                    txtCategoriaEmp.setText("");
                    rbtnSi.setSelected(false);
                    rbtnNo.setSelected(false);
                    txtFechaInicio.setText("");
                    txtFechaFin.setText("");

                    JOptionPane.showMessageDialog(rootPane,"Deshabilitado correctamente");
                  }catch(SQLException | NumberFormatException | HeadlessException x){
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                    }finally {
                        con.desconectar();
                    }
                    
                  
                
                   
//                try{
//                    String sql="UPDATE public.medico\n" +
//"   SET activo=? WHERE codigo=?;";
//
//                    try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
//                        ps.setString(1, rbtnNo.getText());
//                        ps.setInt(2, Integer.parseInt(txtCodigoMedico.getText()));
//                        ps.execute();
//                        ps.close();
//                    } catch (IOException ex) {
//                        Logger.getLogger(frmEliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//
//                    txtNombreApellido.setText("");
//                    txtEspecialidades.setText("");
//                    txtDireccion.setText("");
//                    txtTelefono.setText("");
//                    txtCedula.setText("");
//                    txtSexo.setText("");
//                    txtCorreo.setText("");
//                    txtCodigoMedico.setText("");
//                    txtCategoria.setText("");
//                    txtFechaInicio.setText("");
//                    jpcFechaFin.setDate(null);
//                    
//                    JOptionPane.showMessageDialog(rootPane,"Deshabilitado correctamente");
//                    
//                    txtNombreApellido.setEnabled(false);
//                    txtCedula.setEnabled(false);
//                    txtSexo.setEnabled(false);
//                    txtEspecialidades.setEnabled(false);
//                    txtTelefono.setEnabled(false);
//                    txtDireccion.setEnabled(false);
//                    txtCorreo.setEnabled(false);
//                    txtFechaInicio.setEnabled(false);
//                    jpcFechaFin.setEnabled(false);
//                    
//                }catch(SQLException | NumberFormatException | HeadlessException x){
//                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
//                }finally {
//                    con.desconectar();
//                }
            }
        }
    }//GEN-LAST:event_btnDelAceptarActionPerformed
    
    public void ordenarTabla(){
        TableRowSorter<TableModel> ordenar = new TableRowSorter<>(modelo);
        tablaEmpleadosRegistrados.setRowSorter(ordenar);
    }
    
    public void cargarTabla() throws IOException, SQLException{
        Conexion con = new Conexion();
        con.conectar();
        ResultSet rs = null;
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Cédula");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Correo");
        modelo.addColumn("Título");
        modelo.addColumn("Estado");
        modelo.addColumn("F.Inicio");
        modelo.addColumn("F.Fin");
        modelo.addColumn("Categoria");
        
        try{
            rs = con.ejecutarQuery("SELECT \n" +
"empleado.\"idempleado\", \n" +
"empleado.\"nombre\", \n" +
"empleado.\"apellido\", \n" +
"empleado.\"cedula\", \n" +
"empleado.\"direccion\",\n" +
"empleado.\"telefono\", \n" +
"empleado.\"correo\", \n" +
"empleado.\"titulo\",\n" +
"usuario.\"estado\",\n" +
"contrato.\"fechainicio\",\n" +
"contrato.\"fechafin\",\n" +
"categoria.\"tipo\"\n" +
"FROM public.\"empleado\" empleado INNER JOIN public.\"contrato\" contrato ON\n" +
"contrato.\"idempleado\"=empleado.\"idempleado\" INNER JOIN public.\"usuario\" usuario ON\n" +
"empleado.\"idempleado\"=usuario.\"idempleado\" INNER JOIN public.\"categoriaempleado\" categoria ON\n" +
"empleado.\"idcategoriaempleado\"=categoria.\"idcategoriaempleado\";");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
            rs.close();
        }
        tablaEmpleadosRegistrados.setModel(modelo);
        modelo.fireTableDataChanged();
        
        tablaEmpleadosRegistrados.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaEmpleadosRegistrados.getColumnModel().getColumn(0).setMinWidth(0);
        tablaEmpleadosRegistrados.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void tablaEmpleadosRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosRegistradosMouseClicked
        int selectedRowIndex = tablaEmpleadosRegistrados.rowAtPoint(evt.getPoint());
        txtCodigoEmpleado.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 0).toString());
        txtModNombre.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 1).toString());
        txtModApellido.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 2).toString());
        txtModCedula.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 3).toString());
        txtModDireccion.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 4).toString());
        txtModTelefono.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 5).toString());
        txtRegCorreo.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 6).toString());
        txtEspecialidades.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 7).toString());
        if("activo".equals(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 8).toString())){
            rbtnSi.setEnabled(true);
            rbtnSi.setSelected(true);
        }else{
            rbtnNo.setSelected(true);
        }
        txtFechaInicio.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 9).toString());
        txtFechaFin.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 10).toString());
        txtCategoriaEmp.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 11).toString());
        
        txtModNombre.setCaretPosition(0);
        txtModApellido.setCaretPosition(0);
        txtRegCorreo.setCaretPosition(0);
        
    }//GEN-LAST:event_tablaEmpleadosRegistradosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Conexion con = new Conexion();
        ResultSet rs = null;
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmEliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelo.setRowCount( 0 );
        
        try{
            rs = con.ejecutarQuery("SELECT \n" +
"empleado.\"idempleado\", \n" +
"empleado.\"nombre\", \n" +
"empleado.\"apellido\", \n" +
"empleado.\"cedula\", \n" +
"empleado.\"direccion\",\n" +
"empleado.\"telefono\", \n" +
"empleado.\"correo\", \n" +
"empleado.\"titulo\",\n" +
"usuario.\"estado\",\n" +
"contrato.\"fechainicio\",\n" +
"contrato.\"fechafin\",\n" +
"categoria.\"tipo\"\n" +
"FROM public.\"empleado\" empleado INNER JOIN public.\"contrato\" contrato ON\n" +
"contrato.\"idempleado\"=empleado.\"idempleado\" INNER JOIN public.\"usuario\" usuario ON\n" +
"empleado.\"idempleado\"=usuario.\"idempleado\" INNER JOIN public.\"categoriaempleado\" categoria ON\n" +
"empleado.\"idcategoriaempleado\"=categoria.\"idcategoriaempleado\";");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmEliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmEliminarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tablaEmpleadosRegistrados.setModel(modelo);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        btnActualizar.setToolTipText("Actualizar tabla");
    }//GEN-LAST:event_btnActualizarMouseEntered

    public void filtro() {
        int columnaABuscar = 0;
        if (cmbListar.getSelectedItem().equals("Código")) {
            columnaABuscar = 0;
        }
        if (cmbListar.getSelectedItem() == "Nombre") {
            columnaABuscar = 1;
        }
        if (cmbListar.getSelectedItem() == "Apellido") {
            columnaABuscar = 2;
        }
        if (cmbListar.getSelectedItem() == "Cédula") {
            columnaABuscar = 3;
        }
        String replace = txtBusqueda.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tablaEmpleadosRegistrados.setRowSorter(trsFiltro);
    }
    
    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        txtBusqueda.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusqueda.getText());
                txtBusqueda.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaEmpleadosRegistrados.getModel());
        tablaEmpleadosRegistrados.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void txtModNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModNombreFocusLost
        txtModNombre.setCaretPosition(0);
    }//GEN-LAST:event_txtModNombreFocusLost

    private void txtModDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModDireccionFocusLost
        txtModDireccion.setCaretPosition(0);
    }//GEN-LAST:event_txtModDireccionFocusLost

    private void txtRegCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRegCorreoFocusLost
        txtRegCorreo.setCaretPosition(0);
    }//GEN-LAST:event_txtRegCorreoFocusLost

    private void txtModApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModApellidoFocusLost
        txtModApellido.setCaretPosition(0);
    }//GEN-LAST:event_txtModApellidoFocusLost

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmModificarMedico().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnDelAceptar;
    private javax.swing.JComboBox<String> cmbListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel1;
    private javax.swing.ButtonGroup rbtnGrupoDelete;
    private javax.swing.JRadioButton rbtnNo;
    private javax.swing.JRadioButton rbtnSi;
    private javax.swing.JTable tablaEmpleadosRegistrados;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCategoriaEmp;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtEspecialidades;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtModApellido;
    public static javax.swing.JTextField txtModCedula;
    public static javax.swing.JTextField txtModDireccion;
    public static javax.swing.JTextField txtModNombre;
    public static javax.swing.JTextField txtModTelefono;
    public static javax.swing.JTextField txtRegCorreo;
    // End of variables declaration//GEN-END:variables
}
