/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cebycam.vistas.Administrador;
import ec.com.cebycam.accesodatos.Conexion;
import java.awt.HeadlessException;
import java.awt.event.*;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author lufeb
 */
public final class frmModificarPaciente extends javax.swing.JFrame {
    DefaultTableModel modelo;
    TableRowSorter trsFiltro;
    public static String cedula=null;
    public static int codigo;
    public static String categoria;
    /**
     * Creates new form frmModificarMedico
     * @throws java.io.IOException
     * @throws java.sql.SQLException
     */
    public frmModificarPaciente() throws IOException, SQLException {
        initComponents();
        frmModificarPaciente.txtNombreUsuario.setText(cedula);
        frmModificarPaciente.txtCodigoAdmin.setText(String.valueOf(codigo));
        frmModificarPaciente.txtCategoria.setText(String.valueOf(categoria));
        cargarTabla();
        ordenarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        JRootPane boton = SwingUtilities.getRootPane(btnModPaciente); 
        boton.setDefaultButton(btnModPaciente);
        
        txtCedulaPac.setEnabled(false);
        txtNombrePac.setEnabled(false);
        txtApellidoPac.setEnabled(false);
        txtDirPac.setEnabled(false);
        txtSexoPac.setEnabled(false);
        txtTelPac.setEnabled(false);
        txtCorreoPac.setEnabled(false);
        txtEdadPac.setEnabled(false);
        jdcNacPac.setEnabled(false);
        txtTipoSangrePac.setEnabled(false);
        txtEstadoCivilPac.setEnabled(false);
        txtProfesionPac.setEnabled(false);
        btnModPaciente.setEnabled(false);
        cmbSexoPac.setEnabled(false);
        cmbTipoSangrePac.setEnabled(false);
        cmbEstCivilPac.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleadosRegistrados = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        cmbListar = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedulaPac = new javax.swing.JTextField();
        txtApellidoPac = new javax.swing.JTextField();
        txtTelPac = new javax.swing.JTextField();
        btnModPaciente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtDirPac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtCodigoAdmin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        txtNombrePac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEdadPac = new javax.swing.JTextField();
        cmbTipoSangrePac = new javax.swing.JComboBox<>();
        cmbEstCivilPac = new javax.swing.JComboBox<>();
        txtProfesionPac = new javax.swing.JTextField();
        txtRucPac = new javax.swing.JTextField();
        cmbSexoPac = new javax.swing.JComboBox<>();
        txtCorreoPac = new javax.swing.JTextField();
        jdcNacPac = new com.toedter.calendar.JDateChooser();
        txtSexoPac = new javax.swing.JTextField();
        txtTipoSangrePac = new javax.swing.JTextField();
        txtEstadoCivilPac = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCodPac = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Modificar Paciente");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados "));
        jPanel1.setToolTipText("");

        tablaEmpleadosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaEmpleadosRegistrados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaEmpleadosRegistrados.setAutoscrolls(false);
        tablaEmpleadosRegistrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadosRegistradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleadosRegistrados);

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMouseEntered(evt);
            }
        });
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel16.setText("Buscar por:");

        cmbListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Código", "Cédula", "Nombre", "Apellido" }));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtBusqueda)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel1.setPreferredSize(new java.awt.Dimension(300, 230));

        jLabel3.setText("Cédula:");

        jLabel4.setText("Apellido");

        jLabel5.setText("Sexo:");

        jLabel7.setText("Correo:");

        txtCedulaPac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaPacFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaPacFocusLost(evt);
            }
        });
        txtCedulaPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaPacKeyTyped(evt);
            }
        });

        txtApellidoPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPacKeyTyped(evt);
            }
        });

        txtTelPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelPacKeyTyped(evt);
            }
        });

        btnModPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnModPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPacienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Dirección:");

        txtDirPac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDirPacFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDirPacFocusLost(evt);
            }
        });

        jLabel1.setText("Teléfono:");

        txtNombreUsuario.setEditable(false);
        txtNombreUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigoAdmin.setEditable(false);
        txtCodigoAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoAdmin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bienvenido");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID");

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtNombrePac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePacKeyTyped(evt);
            }
        });

        jLabel6.setText("Nombre:");

        Tipo.setText("Edad:");

        jLabel8.setText("F. Nacimiento:");

        jLabel11.setText("T. Sangre:");

        jLabel12.setText("E. Civil:");

        jLabel13.setText("Profesión:");

        jLabel14.setText("RUC:");

        txtEdadPac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEdadPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadPacKeyTyped(evt);
            }
        });

        cmbTipoSangrePac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A+", "B+", "O+", "AB+", "A-", "B-", "O-", "AB-" }));
        cmbTipoSangrePac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoSangrePacItemStateChanged(evt);
            }
        });

        cmbEstCivilPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));
        cmbEstCivilPac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEstCivilPacItemStateChanged(evt);
            }
        });

        txtRucPac.setEditable(false);
        txtRucPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucPacKeyTyped(evt);
            }
        });

        cmbSexoPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino" }));
        cmbSexoPac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSexoPacItemStateChanged(evt);
            }
        });

        jLabel15.setText("Código:");

        txtCodPac.setEditable(false);
        txtCodPac.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47)
                        .addComponent(txtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(Tipo)
                        .addGap(66, 66, 66)
                        .addComponent(txtEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(43, 43, 43)
                        .addComponent(txtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8)
                        .addGap(25, 25, 25)
                        .addComponent(jdcNacPac, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addGap(47, 47, 47)
                        .addComponent(txtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addGap(43, 43, 43)
                        .addComponent(txtTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cmbTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10)
                        .addGap(37, 37, 37)
                        .addComponent(txtDirPac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel12)
                        .addGap(58, 58, 58)
                        .addComponent(txtEstadoCivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cmbEstCivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(56, 56, 56)
                        .addComponent(txtSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cmbSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel13)
                        .addGap(45, 45, 45)
                        .addComponent(txtProfesionPac, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(txtTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel14))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(47, 47, 47)
                                .addComponent(txtCorreoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel15)))
                        .addGap(57, 57, 57)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRucPac, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtCodPac)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnModPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Tipo))))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jdcNacPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoSangrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDirPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoCivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstCivilPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSexoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfesionPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))))
                .addGap(17, 17, 17)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRucPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14))))
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(btnModPaciente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void ordenarTabla(){
        TableRowSorter<TableModel> ordenar = new TableRowSorter<>(modelo);
        tablaEmpleadosRegistrados.setRowSorter(ordenar);
    }
    
    public void cargarTabla() throws IOException, SQLException{
        Conexion con = new Conexion();
        con.conectar();
        ResultSet rs = null;
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Cédula");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Dirección");
        modelo.addColumn("Sexo");
        modelo.addColumn("Telefono");
        modelo.addColumn("Correo");
        modelo.addColumn("Edad");
        modelo.addColumn("F.Nacimiento");
        modelo.addColumn("T.Sangre");
        modelo.addColumn("E.Civil");
        modelo.addColumn("Profesión");
        modelo.addColumn("ruc");
        
        try{
            rs = con.ejecutarQuery("SELECT idpaciente, cedula, nombre, apellido, direccion, sexo, telefono, correo, edad, fechanacimiento, tiposangre, estadocivil, profesion, ruc\n" +
"	FROM public.paciente;");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
            rs.close();
        }
        tablaEmpleadosRegistrados.setModel(modelo);
        modelo.fireTableDataChanged();
        
        tablaEmpleadosRegistrados.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaEmpleadosRegistrados.getColumnModel().getColumn(0).setMinWidth(0);
        tablaEmpleadosRegistrados.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void tablaEmpleadosRegistradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadosRegistradosMouseClicked
        int selectedRowIndex = tablaEmpleadosRegistrados.rowAtPoint(evt.getPoint());
        txtCodPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 0).toString());
        txtCedulaPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 1).toString());
        txtNombrePac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 2).toString());
        txtApellidoPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 3).toString());
        txtDirPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 4).toString());
        txtSexoPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 5).toString());
        txtTelPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 6).toString());
        txtCorreoPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex, 7).toString());
        txtEdadPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex,8).toString());
        jdcNacPac.setDate(Date.valueOf(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex,9).toString()));
        txtTipoSangrePac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex,10).toString());        
        txtEstadoCivilPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex,11).toString());        
        txtProfesionPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex,12).toString());
        txtRucPac.setText(tablaEmpleadosRegistrados.getValueAt(selectedRowIndex,13).toString());        
                
        txtNombrePac.setCaretPosition(0);
        txtApellidoPac.setCaretPosition(0);
        txtDirPac.setCaretPosition(0);
        txtCorreoPac.setCaretPosition(0);
        
        txtCedulaPac.setEnabled(true);
        txtNombrePac.setEnabled(true);
        txtApellidoPac.setEnabled(true);
        txtDirPac.setEnabled(true);
        txtSexoPac.setEnabled(true);
        txtTelPac.setEnabled(true);
        txtCorreoPac.setEnabled(true);
        txtEdadPac.setEnabled(true);
        jdcNacPac.setEnabled(true);
        txtTipoSangrePac.setEnabled(true);
        txtEstadoCivilPac.setEnabled(true);
        txtProfesionPac.setEnabled(true);
        btnModPaciente.setEnabled(true);
        cmbSexoPac.setEnabled(true);
        cmbTipoSangrePac.setEnabled(true);
        cmbEstCivilPac.setEnabled(true);
    }//GEN-LAST:event_tablaEmpleadosRegistradosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Conexion con = new Conexion();
        ResultSet rs = null;
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelo.setRowCount( 0 );
        
        try{
            rs = con.ejecutarQuery("SELECT idpaciente, cedula, nombre, apellido, direccion, sexo, telefono, correo, edad, fechanacimiento, tiposangre, estadocivil, profesion, ruc\n" +
"	FROM public.paciente;");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tablaEmpleadosRegistrados.setModel(modelo);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseEntered
        btnActualizar.setToolTipText("Actualizar tabla");
    }//GEN-LAST:event_btnActualizarMouseEntered

    public void filtro() {
        int columnaABuscar = 0;
        if (cmbListar.getSelectedItem().equals("Código")) {
            columnaABuscar = 0;
        }
        if (cmbListar.getSelectedItem() == "Cédula") {
            columnaABuscar = 1;
        }
        if (cmbListar.getSelectedItem() == "Nombre") {
            columnaABuscar = 2;
        }
        if (cmbListar.getSelectedItem() == "Apellido") {
            columnaABuscar = 3;
        }
        
        String replace = txtBusqueda.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tablaEmpleadosRegistrados.setRowSorter(trsFiltro);
    }
    
    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        txtBusqueda.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusqueda.getText());
                txtBusqueda.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaEmpleadosRegistrados.getModel());
        tablaEmpleadosRegistrados.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void txtCedulaPacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaPacFocusGained
        txtCedulaPac.setCaretPosition(0);
    }//GEN-LAST:event_txtCedulaPacFocusGained

    private void txtCedulaPacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaPacFocusLost
        txtCedulaPac.setCaretPosition(0);
        String ruc = txtCedulaPac.getText()+"001";
        txtRucPac.setText(ruc);
    }//GEN-LAST:event_txtCedulaPacFocusLost

    private void txtCedulaPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtCedulaPac.getText().length() == 10)
        evt.consume();
    }//GEN-LAST:event_txtCedulaPacKeyTyped

    private void txtApellidoPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b!=0){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoPacKeyTyped

    private void txtTelPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtTelPac.getText().length() == 10)
        evt.consume();
    }//GEN-LAST:event_txtTelPacKeyTyped

    private void btnModPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPacienteActionPerformed
        Conexion con= new Conexion();

        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAdminPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        if(txtCedulaPac.getText().equals("")||txtNombrePac.getText().equals("")||txtApellidoPac.getText().equals("")||txtDirPac.getText().equals("")
                ||txtSexoPac.getText().equals("")||txtTelPac.getText().equals("")||txtCorreoPac.getText().equals("")||txtEdadPac.getText().equals("")
                ||jdcNacPac.getDate()==null||txtTipoSangrePac.getText().equals("")||txtEstadoCivilPac.getText().equals("")
                ||txtProfesionPac.getText().equals("")||txtRucPac.getText().equals("")||txtCodPac.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                String insertarCategoria="UPDATE public.paciente\n" +
"	SET cedula=?, nombre=?, apellido=?, direccion=?, sexo=?, telefono=?, correo=?, edad=?, fechanacimiento=?, tiposangre=?, estadocivil=?, profesion=?, ruc=?\n" +
"	WHERE idpaciente=?;";
                try (PreparedStatement ps = con.conectar().prepareStatement(insertarCategoria)) {
                    ps.setString(1, txtCedulaPac.getText());
                    ps.setString(2, txtNombrePac.getText());
                    ps.setString(3, txtApellidoPac.getText());
                    ps.setString(4, txtDirPac.getText());
                    ps.setString(5, txtSexoPac.getText());
                    ps.setString(6, txtTelPac.getText());
                    ps.setString(7, txtCorreoPac.getText());
                    ps.setInt(8, Integer.parseInt(txtEdadPac.getText()));
                    ps.setDate(9, new java.sql.Date(jdcNacPac.getDate().getTime()));
                    ps.setString(10, txtTipoSangrePac.getText());
                    ps.setString(11, txtEstadoCivilPac.getText());
                    ps.setString(12, txtProfesionPac.getText());
                    ps.setString(13, txtRucPac.getText());
                    ps.setInt(14, Integer.parseInt(txtCodPac.getText()));

                    ps.execute();
                    ps.close();
                } catch (IOException ex) {
                    Logger.getLogger(frmAdminPaciente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }catch(SQLException | NumberFormatException | HeadlessException x){
                JOptionPane.showMessageDialog(rootPane, "Error al guardar la información "+x);
            }finally {
                con.desconectar();
            }

            txtCedulaPac.setText("");
            txtNombrePac.setText("");
            txtApellidoPac.setText("");
            txtDirPac.setText("");
            txtSexoPac.setText("");
            cmbSexoPac.setSelectedItem("Seleccione");
            txtTelPac.setText("");
            txtCorreoPac.setText("");
            txtEdadPac.setText("");
            jdcNacPac.setDate(null);
            txtTipoSangrePac.setText("");
            cmbTipoSangrePac.setSelectedItem("Seleccione");
            txtEstadoCivilPac.setText("");
            cmbEstCivilPac.setSelectedItem("Seleccione");
            txtProfesionPac.setText("");
            txtRucPac.setText("");
            txtCodPac.setText("");

            JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");

        }
        }
    }//GEN-LAST:event_btnModPacienteActionPerformed

    private void txtDirPacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDirPacFocusGained
        txtDirPac.setCaretPosition(0);
    }//GEN-LAST:event_txtDirPacFocusGained

    private void txtDirPacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDirPacFocusLost
        txtDirPac.setCaretPosition(0);
    }//GEN-LAST:event_txtDirPacFocusLost

    private void txtNombrePacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b!=0){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombrePacKeyTyped

    private void txtEdadPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadPacKeyTyped

    private void txtRucPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtRucPac.getText().length() == 13)
        evt.consume();
    }//GEN-LAST:event_txtRucPacKeyTyped

    private void cmbTipoSangrePacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoSangrePacItemStateChanged
        if(cmbTipoSangrePac.getSelectedItem().toString().equals("Seleccione")){
            txtTipoSangrePac.setText("");
        }else{
            txtTipoSangrePac.setText(cmbTipoSangrePac.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbTipoSangrePacItemStateChanged

    private void cmbEstCivilPacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEstCivilPacItemStateChanged
        if(cmbEstCivilPac.getSelectedItem().toString().equals("Seleccione")){
            txtEstadoCivilPac.setText("");
        }else{
            txtEstadoCivilPac.setText(cmbEstCivilPac.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbEstCivilPacItemStateChanged

    private void cmbSexoPacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSexoPacItemStateChanged
        if(cmbSexoPac.getSelectedItem().toString().equals("Seleccione")){
            txtSexoPac.setText("");
        }else{
            txtSexoPac.setText(cmbSexoPac.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cmbSexoPacItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmModificarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmModificarMedico().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tipo;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnModPaciente;
    private javax.swing.JComboBox<String> cmbEstCivilPac;
    private javax.swing.JComboBox<String> cmbListar;
    private javax.swing.JComboBox<String> cmbSexoPac;
    private javax.swing.JComboBox<String> cmbTipoSangrePac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcNacPac;
    private javax.swing.JPanel panel1;
    private javax.swing.JTable tablaEmpleadosRegistrados;
    public static javax.swing.JTextField txtApellidoPac;
    private javax.swing.JTextField txtBusqueda;
    public static javax.swing.JTextField txtCategoria;
    public static javax.swing.JTextField txtCedulaPac;
    private javax.swing.JTextField txtCodPac;
    public static javax.swing.JTextField txtCodigoAdmin;
    private javax.swing.JTextField txtCorreoPac;
    public static javax.swing.JTextField txtDirPac;
    private javax.swing.JTextField txtEdadPac;
    private javax.swing.JTextField txtEstadoCivilPac;
    private javax.swing.JTextField txtNombrePac;
    public static javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtProfesionPac;
    private javax.swing.JTextField txtRucPac;
    private javax.swing.JTextField txtSexoPac;
    public static javax.swing.JTextField txtTelPac;
    private javax.swing.JTextField txtTipoSangrePac;
    // End of variables declaration//GEN-END:variables
}
