/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cebycam.vistas;

import ec.com.cebycam.vistas.Medico.frmPrincipal;
import ec.com.cebycam.accesodatos.Conexion;
import ec.com.cebycam.dao.impl.CambioContraseñaImp;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author lufeb
 */
public final class frmCambiarClave extends javax.swing.JFrame {
    private final int cedula  = 10;
    
    /**
     * Creates new form frmCambiarCable
     */
    
    @SuppressWarnings("empty-statement")
    public void cerrar(){
        if (JOptionPane.showConfirmDialog(this, "¿Desea realmente salir del sistema?",
                "CEBYCAM-CES", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            this.setDefaultCloseOperation(frmPrincipal.DISPOSE_ON_CLOSE);;
        }
    }
    
    public frmCambiarClave() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        JRootPane boton = SwingUtilities.getRootPane(btnCheckDatos); 
        boton.setDefaultButton(btnCheckDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRecuperacion = new javax.swing.JPasswordField();
        btnCheckDatos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pwdNuevaClave = new javax.swing.JPasswordField();
        pwdRepetirClave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Nueva Clave");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos de Acceso"));

        jLabel1.setText("Usuario");

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });

        jLabel2.setText("Palabra secreta");

        btnCheckDatos.setText("Aceptar");
        btnCheckDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(txtRecuperacion)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnCheckDatos)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRecuperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCheckDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Nueva Contraseña"));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 152));

        jLabel3.setText("Nueva contraseña");

        pwdNuevaClave.setEnabled(false);

        pwdRepetirClave.setEnabled(false);

        jLabel4.setText("Repetir clave");

        btnAceptar.setText("Aceptar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdNuevaClave)
                    .addComponent(pwdRepetirClave)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwdNuevaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdRepetirClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmCambiarClave.class.getName()).log(Level.SEVERE, null, ex);
        }
        CambioContraseñaImp login = new CambioContraseñaImp();
        String clave = String.valueOf(pwdNuevaClave.getPassword());
        String clave2= String.valueOf(pwdRepetirClave.getPassword());
        
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(clave.equals("")&&clave2.equals("")){
                JOptionPane.showMessageDialog(this, "Debe ingresar su nueva clave",
                            "CEBYCAM-CES", JOptionPane.ERROR_MESSAGE);
            }else{
                if(Arrays.equals(pwdNuevaClave.getPassword(), pwdRepetirClave.getPassword())){
                    try {
                        ///MEDICO
                        if(login.CambioContraseñaImp()==1){
                            try{
                                String sql="UPDATE public.usuario\n" +
                                        "   SET clave=? WHERE usuario=?;";
                                
                                try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                                    ps.setString(1, String.valueOf(pwdNuevaClave.getPassword()));
                                    ps.setString(2, txtUsuario.getText());
                                    ps.execute();
                                    ps.close();
                                }
                                JOptionPane.showMessageDialog(this, "Clave cambiada correctamente\n      El sistema se cerrará",
                                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                                System.exit(0);
                            }catch(SQLException | NumberFormatException | HeadlessException x){
                                JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                            }finally {
                                con.desconectar();
                            }
                        }else{
                            ///ADMINISTRADOR
                            if(login.CambioContraseñaImpAdmin()==1){
                                try{
                                    String sql="UPDATE public.administrador SET clave=? WHERE cedula=?;";
                                    
                                    try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                                        ps.setString(1, String.valueOf(pwdNuevaClave.getPassword()));
                                        ps.setString(2, txtUsuario.getText());
                                        ps.execute();
                                        ps.close();
                                    }
                                    JOptionPane.showMessageDialog(this, "Clave cambiada correctamente\n      El sistema se cerrará",
                                            "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                                    System.exit(0);
                                }catch(SQLException | NumberFormatException | HeadlessException x){
                                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                                }finally {
                                    con.desconectar();
                                }
                            }else{
                                ///ENFERMERIA
                                try{
                                    String sql="UPDATE public.enfermeria SET clave=? WHERE cedula=?;";
                                    
                                    try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                                        ps.setString(1, String.valueOf(pwdNuevaClave.getPassword()));
                                        ps.setString(2, txtUsuario.getText());
                                        ps.execute();
                                        ps.close();
                                    }
                                    JOptionPane.showMessageDialog(this, "Clave cambiada correctamente\n      El sistema se cerrará",
                                            "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                                    System.exit(0);
                                }catch(SQLException | NumberFormatException | HeadlessException x){
                                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                                }finally {
                                    con.desconectar();
                                }
                            }
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(frmCambiarClave.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Las claves no concuerdan", "CEBYCAM-CES",
                            JOptionPane.ERROR_MESSAGE);
                    pwdNuevaClave.setText("");
                    pwdRepetirClave.setText("");
                    pwdNuevaClave.requestFocus();
                }
            }
        } 
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
//        char []p={'1','2','3','4','5','6','7','8','9','0'};
//        int b=0;
//        for(int i=0;i<=9;i++){
//            if (p[i]==evt.getKeyChar()){
//                b=1;
//            }
//        }
//        if(b==0){
//            evt.consume();
//        }
//        if (txtUsuario.getText().length() == cedula)  
//             evt.consume();
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void btnCheckDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckDatosActionPerformed
        CambioContraseñaImp login = new CambioContraseñaImp();
        if(txtUsuario.getText().equals("")||txtRecuperacion.getPassword().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar sus datos",
                    "CEBYCAM-CES", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
                if(login.CambioContraseñaImp()==1){
                    JOptionPane.showMessageDialog(this, "       Usuario encontrado",
                            "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                    pwdNuevaClave.setEnabled(true);
                    pwdRepetirClave.setEnabled(true);
                    btnAceptar.setEnabled(true);
                    txtUsuario.setEnabled(false);
                    txtRecuperacion.setEnabled(false);
                    btnCheckDatos.setEnabled(false);
                    JRootPane boton = SwingUtilities.getRootPane(btnAceptar); 
                    boton.setDefaultButton(btnAceptar);
                }else{
                    if(login.CambioContraseñaImpAdmin()==1){
                        JOptionPane.showMessageDialog(this, "       Usuario encontrado",
                                "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                        pwdNuevaClave.setEnabled(true);
                        pwdRepetirClave.setEnabled(true);
                        btnAceptar.setEnabled(true);
                        txtUsuario.setEnabled(false);
                        txtRecuperacion.setEnabled(false);
                        btnCheckDatos.setEnabled(false);
                        JRootPane boton = SwingUtilities.getRootPane(btnAceptar); 
                        boton.setDefaultButton(btnAceptar);
                    }else{
                        if(login.CambioContraseñaImpEnfermeria()==1){
                            JOptionPane.showMessageDialog(this, "       Usuario encontrado",
                                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                            pwdNuevaClave.setEnabled(true);
                            pwdRepetirClave.setEnabled(true);
                            btnAceptar.setEnabled(true);
                            txtUsuario.setEnabled(false);
                            txtRecuperacion.setEnabled(false);
                            btnCheckDatos.setEnabled(false);
                            JRootPane boton = SwingUtilities.getRootPane(btnAceptar);
                            boton.setDefaultButton(btnAceptar);
                        }else{
                            JOptionPane.showMessageDialog(this, "       Usuario no encontrado",
                                    "CEBYCAM-CES", JOptionPane.ERROR_MESSAGE);
                            txtUsuario.setText("");
                            txtRecuperacion.setText("");
                            txtUsuario.requestFocus();
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(frmCambiarClave.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnCheckDatosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCheckDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JPasswordField pwdNuevaClave;
    private javax.swing.JPasswordField pwdRepetirClave;
    public static javax.swing.JPasswordField txtRecuperacion;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
