/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cebycam.vistas.Enfermeria;

import ec.com.cebycam.vistas.Medico.frmAtencionPaciente;
import ec.com.cebycam.accesodatos.Conexion;
import java.awt.HeadlessException;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.*;
import org.imgscalr.Scalr;

/**
 *
 * @author User
 */
public final class frmModificarSV extends javax.swing.JFrame {
    public static int codigo;
    public static String nombreEnfermero;
    public static String categoria;
    DefaultTableModel modelo;
    TableRowSorter trsFiltro;
    
    /**
     * Creates new form frm
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public frmModificarSV() throws SQLException, IOException {
        initComponents();
        cargaTabla();
        ordenarTabla();
        frmModificarSV.txtIdEnfermeros.setText(String.valueOf(codigo));
        frmModificarSV.txtNombreEnfermero.setText(nombreEnfermero);
        frmModificarSV.txtCategoria.setText(categoria);
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(frmModificarSV.DISPOSE_ON_CLOSE);
        consultar_medicos();
        JRootPane boton = SwingUtilities.getRootPane(btnGuardarSignosVitalesPac); 
        boton.setDefaultButton(btnGuardarSignosVitalesPac);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtNombrePac = new javax.swing.JTextField();
        txtCedulaPac = new javax.swing.JTextField();
        txtEdadPac = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtCodigoHistoria = new javax.swing.JTextField();
        lblFotoPac = new javax.swing.JLabel();
        txtCategoriaPaciente = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtHoraPac = new javax.swing.JTextField();
        txtTemperaturaPac = new javax.swing.JTextField();
        txtFrecuenciaCardiacaPac = new javax.swing.JTextField();
        txtSatO2Pac = new javax.swing.JTextField();
        txtPresionArtPac = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtAntecedentesPac = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtPacAlergias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPacSintomas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaPac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuardarSignosVitalesPac = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        txtIdEnfermeros = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtNombreEnfermero = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaSignosVitalesPac = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        cmbListarPac = new javax.swing.JComboBox<>();
        txtBusquedaPac = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbMedicos = new javax.swing.JComboBox<>();
        txtCategoria = new javax.swing.JTextField();
        txtIdSV = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Modificar SV");
        setResizable(false);

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("SIGNOS VITALES");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Paciente"));

        jLabel32.setText("Nombres:");

        jLabel33.setText("Cédula:");

        jLabel34.setText("Edad:");

        txtNombrePac.setEditable(false);
        txtNombrePac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombrePac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombrePacFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombrePacFocusLost(evt);
            }
        });

        txtCedulaPac.setEditable(false);
        txtCedulaPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEdadPac.setEditable(false);
        txtEdadPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel37.setText("Código H.Clínica");

        txtCodigoHistoria.setEditable(false);
        txtCodigoHistoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblFotoPac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCategoriaPaciente.setEditable(false);
        txtCategoriaPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoriaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblFotoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(43, 43, 43)
                        .addComponent(txtNombrePac))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCategoriaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoHistoria))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(52, 52, 52)
                                .addComponent(txtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(61, 61, 61)
                                .addComponent(txtEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel32))
                    .addComponent(txtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(txtCategoriaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel33))
                    .addComponent(txtCedulaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel34))
                    .addComponent(txtEdadPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFotoPac.getAccessibleContext().setAccessibleParent(this);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Atención"));

        jLabel38.setText("Hora:");

        jLabel39.setText("Temperatura:");

        jLabel40.setText("Frecuencia Cardiaca:");

        jLabel41.setText("Saturación Oxígeno:");

        jLabel42.setText("Presión Arterial:");

        txtTemperaturaPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTemperaturaPacKeyTyped(evt);
            }
        });

        txtFrecuenciaCardiacaPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFrecuenciaCardiacaPacKeyTyped(evt);
            }
        });

        txtSatO2Pac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSatO2PacKeyTyped(evt);
            }
        });

        txtPresionArtPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPresionArtPacKeyTyped(evt);
            }
        });

        jLabel35.setText("Antecedentes:");

        txtAntecedentesPac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAntecedentesPacFocusLost(evt);
            }
        });

        jLabel36.setText("Alergias:");

        txtPacAlergias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPacAlergiasFocusLost(evt);
            }
        });

        jLabel1.setText("Sintomas");

        txtPacSintomas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPacSintomasFocusLost(evt);
            }
        });

        jLabel2.setText("Fecha:");

        jLabel4.setText("0.0");

        jLabel5.setText("0.0");

        jLabel6.setText("0.0");

        jLabel7.setText("0/0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaPac)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPacAlergias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addComponent(txtAntecedentesPac, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPacSintomas, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPresionArtPac, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSatO2Pac, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFrecuenciaCardiacaPac, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTemperaturaPac, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHoraPac, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(txtHoraPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtTemperaturaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(txtFrecuenciaCardiacaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(txtSatO2Pac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(txtPresionArtPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPacSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtAntecedentesPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(txtPacAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        btnGuardarSignosVitalesPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnGuardarSignosVitalesPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSignosVitalesPacActionPerformed(evt);
            }
        });

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("ID");

        txtIdEnfermeros.setEditable(false);
        txtIdEnfermeros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdEnfermeros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel44.setText("Bienvenido");

        txtNombreEnfermero.setEditable(false);
        txtNombreEnfermero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreEnfermero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Pacientes"));

        tablaSignosVitalesPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaSignosVitalesPac.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaSignosVitalesPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaSignosVitalesPacMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaSignosVitalesPac);

        jLabel45.setText("Buscar por:");

        cmbListarPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H.Clinica", "Nombre", "Cédula" }));

        txtBusquedaPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaPacKeyTyped(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel45)
                        .addGap(10, 10, 10)
                        .addComponent(cmbListarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusquedaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel45))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbListarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusquedaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Médico Tratante"));

        jLabel3.setText("Lista de Médicos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdSV.setEditable(false);
        txtIdSV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdSV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setText(" ID S.V");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel31))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(btnGuardarSignosVitalesPac, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdSV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel44)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdEnfermeros, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEnfermeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardarSignosVitalesPac)
                                .addGap(25, 25, 25))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void ordenarTabla(){
        TableRowSorter<TableModel>ordenar = new TableRowSorter<>(modelo);
        tablaSignosVitalesPac.setRowSorter(ordenar);
    }
    
    public void cargaTabla() throws SQLException, IOException{
        Conexion con = new Conexion();
        con.conectar();
        ResultSet rs = null;
        
        modelo = new DefaultTableModel();
        modelo.addColumn("H.Clinica");
        modelo.addColumn("Paciente");
        modelo.addColumn("Cédula");
        modelo.addColumn("Edad");
        modelo.addColumn("Foto");
        modelo.addColumn("Categoria");
        
        modelo.addColumn("Id.Atencion");
        modelo.addColumn("Hora");
        modelo.addColumn("temperatura");
        modelo.addColumn("F.Cardiaca");
        modelo.addColumn("Saturacion");
        modelo.addColumn("P.Arterial");
        modelo.addColumn("Sintomas");
        modelo.addColumn("Antecedentes");
        modelo.addColumn("Alergias");
        modelo.addColumn("Fecha");
        
        try{
            rs = con.ejecutarQuery("SELECT \n" +
"paciente.\"codigo\", \n" + 
"paciente.\"paciente\" as nombre, \n" + 
"paciente.\"cedula\", \n" +
"paciente.\"edad\", \n" + 
"paciente.\"foto\", \n" + 
"paciente.\"categoria\", \n" + 
"signos_vitales.\"codigo\" as id, \n" +                    
"signos_vitales.\"hora\", \n" +
"signos_vitales.\"temperatura\", \n" +
"signos_vitales.\"frecuencia cardiaca\", \n" +
"signos_vitales.\"saturacion\", \n" +
"signos_vitales.\"presion arterial\", \n" +
"signos_vitales.\"sintomas\", \n" +
"signos_vitales.\"antecedentes\", \n" +
"signos_vitales.\"alergias\", \n" +
"signos_vitales.\"fecha\" \n" +
"FROM public.\"signos vitales\" signos_vitales inner join public.\"historia clinica\" paciente on signos_vitales.paciente=paciente.codigo;");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
            rs.close();
        }
        tablaSignosVitalesPac.setModel(modelo);
        modelo.fireTableDataChanged();
        
        
        tablaSignosVitalesPac.getColumnModel().getColumn(4).setMaxWidth(0);
        tablaSignosVitalesPac.getColumnModel().getColumn(4).setMinWidth(0);
        tablaSignosVitalesPac.getColumnModel().getColumn(4).setPreferredWidth(0);
        
        tablaSignosVitalesPac.getColumnModel().getColumn(5).setMaxWidth(0);
        tablaSignosVitalesPac.getColumnModel().getColumn(5).setMinWidth(0);
        tablaSignosVitalesPac.getColumnModel().getColumn(5).setPreferredWidth(0);
    }
    
    public void filtro() {
        int columnaABuscar = 0;
        if (cmbListarPac.getSelectedItem().equals("H.Clinica")) {
            columnaABuscar = 0;
        }
        if (cmbListarPac.getSelectedItem() == "Nombre") {
            columnaABuscar = 1;
        }
        if (cmbListarPac.getSelectedItem() == "Cédula") {
            columnaABuscar = 2;
        }
        String replace = txtBusquedaPac.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tablaSignosVitalesPac.setRowSorter(trsFiltro);
    }
    
    public void consultar_medicos() throws SQLException, IOException{
        Conexion con= new Conexion();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT nombre, activo FROM public.medico where activo='SI' ORDER BY nombre ASC";
        try {
           pst=con.conectar().prepareStatement(sql);
           rs = pst.executeQuery();
           cmbMedicos.addItem("Seleccione una opción");
           while(rs.next()){
               cmbMedicos.addItem(rs.getString("nombre"));
           }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos de los médicos",
                    "CEBYCAM-CES", JOptionPane.ERROR_MESSAGE);
        }finally{
            con.desconectar();
            rs.close();
        }
    }
    
    private void tablaSignosVitalesPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaSignosVitalesPacMouseClicked
        int selectedRowIndex = tablaSignosVitalesPac.rowAtPoint(evt.getPoint());
        txtCodigoHistoria.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 0).toString());
        txtNombrePac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 1).toString());
        txtCedulaPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 2).toString());
        txtEdadPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 3).toString());
        byte[] byteArray = (byte[]) tablaSignosVitalesPac.getValueAt(selectedRowIndex, 4);

        if(byteArray ==null){
            lblFotoPac.setIcon(null);
            lblFotoPac.setText("     SIN IMAGEN");
        }else{
            ByteArrayInputStream bais = new ByteArrayInputStream(byteArray);
            BufferedImage bImg;

            try {
                bImg = ImageIO.read(bais);
                bImg= Scalr.resize(bImg, Scalr.Method.SPEED, Scalr.Mode.FIT_EXACT, 90, 110);
                lblFotoPac.setIcon(new javax.swing.ImageIcon(bImg));
                bais.close();
            } catch (IOException ex) {
                Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtCategoriaPaciente.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 5).toString());
        
        txtIdSV.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 6).toString());
        txtHoraPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 7).toString());
        txtTemperaturaPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 8).toString());
        txtFrecuenciaCardiacaPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 9).toString());
        txtSatO2Pac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 10).toString());
        txtPresionArtPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 11).toString());
        txtPacSintomas.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 12).toString());
        txtAntecedentesPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 13).toString());  
        txtPacAlergias.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 14).toString()); 
        txtFechaPac.setText(tablaSignosVitalesPac.getValueAt(selectedRowIndex, 15).toString());
    }//GEN-LAST:event_tablaSignosVitalesPacMouseClicked
    
    private void txtBusquedaPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPacKeyTyped
        txtBusquedaPac.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusquedaPac.getText());
                txtBusquedaPac.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaSignosVitalesPac.getModel());
        tablaSignosVitalesPac.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaPacKeyTyped
    
    private void btnGuardarSignosVitalesPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSignosVitalesPacActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmModificarSV.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(txtHoraPac.getText().equals("")||txtTemperaturaPac.getText().equals("")||txtFrecuenciaCardiacaPac.getText().equals("")||txtSatO2Pac.getText().equals("")||
                    txtPresionArtPac.getText().equals("")||txtNombrePac.getText().equals("")||txtCodigoHistoria.getText().equals("")||txtCedulaPac.getText().equals("")||txtEdadPac.getText().equals("")
                            ||txtAntecedentesPac.getText().equals("")||txtPacAlergias.getText().equals("")||cmbMedicos.getSelectedItem().equals("Seleccione una opción")){
                JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                try{
                    String sql="UPDATE public.\"signos vitales\"\n" +
"   SET hora=?, temperatura=?, \"frecuencia cardiaca\"=?, saturacion=?, \n" +
"       \"presion arterial\"=?, sintomas=?, antecedentes=?, alergias=?, \n" +
"       fecha=?, medico=?\n" +
" WHERE codigo="+Integer.parseInt(txtIdSV.getText());

                    try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                        ps.setTime(1, Time.valueOf(txtHoraPac.getText()));
                        ps.setDouble(2, Double.parseDouble(txtTemperaturaPac.getText()));
                        ps.setDouble(3, Double.parseDouble(txtFrecuenciaCardiacaPac.getText()));
                        ps.setDouble(4, Double.parseDouble(txtSatO2Pac.getText()));
                        ps.setString(5, txtPresionArtPac.getText());
                        ps.setString(6, txtPacSintomas.getText());
                        ps.setString(7, txtAntecedentesPac.getText());
                        ps.setString(8, txtPacAlergias.getText());
                        ps.setDate(9, Date.valueOf(txtFechaPac.getText()));
                        ps.setString(10, cmbMedicos.getSelectedItem().toString());
                        ps.execute();
                        ps.close();
                    } catch (IOException ex) {
                        Logger.getLogger(frmModificarSV.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    JOptionPane.showMessageDialog(this, "Datos guardados correctamente...",
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                }catch(SQLException | NumberFormatException | HeadlessException x){
                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                }finally {
                    con.desconectar();
                }
            }
        }
    }//GEN-LAST:event_btnGuardarSignosVitalesPacActionPerformed

    private void txtNombrePacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrePacFocusGained
        txtNombrePac.setCaretPosition(0);
    }//GEN-LAST:event_txtNombrePacFocusGained

    private void txtNombrePacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombrePacFocusLost
        txtNombrePac.setCaretPosition(0);
    }//GEN-LAST:event_txtNombrePacFocusLost

    private void txtTemperaturaPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTemperaturaPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtTemperaturaPacKeyTyped

    private void txtFrecuenciaCardiacaPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFrecuenciaCardiacaPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtFrecuenciaCardiacaPacKeyTyped

    private void txtSatO2PacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSatO2PacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtSatO2PacKeyTyped

    private void txtPresionArtPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresionArtPacKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','/'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtPresionArtPacKeyTyped

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Conexion con = new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmModificarSV.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs = null;
        modelo.setRowCount( 0 );
        try{
            rs = con.ejecutarQuery("SELECT codigo, paciente, cedula, edad, foto, categoria\n" +
"  FROM public.\"historia clinica\";");
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                    modelo.fireTableDataChanged();
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmModificarSV.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmModificarSV.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtPacSintomasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPacSintomasFocusLost
        txtPacSintomas.setCaretPosition(0);
    }//GEN-LAST:event_txtPacSintomasFocusLost

    private void txtAntecedentesPacFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAntecedentesPacFocusLost
        txtAntecedentesPac.setCaretPosition(0);
    }//GEN-LAST:event_txtAntecedentesPacFocusLost

    private void txtPacAlergiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPacAlergiasFocusLost
        txtPacAlergias.setCaretPosition(0);
    }//GEN-LAST:event_txtPacAlergiasFocusLost
        
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarSignosVitalesPac;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbListarPac;
    private javax.swing.JComboBox<String> cmbMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblFotoPac;
    private javax.swing.JTable tablaSignosVitalesPac;
    public static javax.swing.JTextField txtAntecedentesPac;
    private javax.swing.JTextField txtBusquedaPac;
    public static javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCategoriaPaciente;
    public static javax.swing.JTextField txtCedulaPac;
    public static javax.swing.JTextField txtCodigoHistoria;
    public static javax.swing.JTextField txtEdadPac;
    private javax.swing.JTextField txtFechaPac;
    public static javax.swing.JTextField txtFrecuenciaCardiacaPac;
    public static javax.swing.JTextField txtHoraPac;
    public static javax.swing.JTextField txtIdEnfermeros;
    private javax.swing.JTextField txtIdSV;
    public static javax.swing.JTextField txtNombreEnfermero;
    public static javax.swing.JTextField txtNombrePac;
    public static javax.swing.JTextField txtPacAlergias;
    public static javax.swing.JTextField txtPacSintomas;
    public static javax.swing.JTextField txtPresionArtPac;
    public static javax.swing.JTextField txtSatO2Pac;
    public static javax.swing.JTextField txtTemperaturaPac;
    // End of variables declaration//GEN-END:variables
}
