/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cebycam.vistas.Enfermeria;

import ec.com.cebycam.accesodatos.Conexion;
import ec.com.cebycam.rnegocio.entidades.frmCamaraModificarPac;
import ec.com.cebycam.dao.impl.HistoriaClinicaImp;
import ec.com.cebycam.rnegocio.entidades.HistoriaClinica;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.beans.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.*;
import org.imgscalr.Scalr;

/**
 *
 * @author lufeb
 */
public final class frmModificarPaciente extends javax.swing.JFrame {
    JLabel img;
    JButton open;
    JFileChooser jf=new JFileChooser();
    TableRowSorter trsFiltro;
    DefaultTableModel modelo;
    FileInputStream fis;
    int longitudBytes;
    File fichero;
    public static int codigo;
    public static String nombreEnfermero;
    public static String categoria;
    public static String botones = null;
    /**
     * Creates new form frm
     * @throws java.io.IOException
     */
    public frmModificarPaciente() throws IOException {
        initComponents();
        createAndShowGUI();
        cargarTabla();
        ordenarTabla();
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(frmEnfermeria.DISPOSE_ON_CLOSE);
        JRootPane boton = SwingUtilities.getRootPane(btnGuardar); 
        boton.setDefaultButton(btnGuardar);
        frmModificarPaciente.txtIdEnfermero.setText(String.valueOf(codigo));
        txtLoginMed.setText(nombreEnfermero);
        frmModificarPaciente.txtCategoria.setText(categoria);
        
        this.btnSubirFoto.setEnabled(false);
        this.btnCamara.setEnabled(false);
        frmModificarPaciente.txtCedula.setEnabled(false);
        this.txtPaciente.setEnabled(false);
        this.txtEdad.setEnabled(false);
        this.txtSexo.setEnabled(false);
        this.txtEstatura.setEnabled(false);
        this.txtDirecion.setEnabled(false);
        this.jpcFechaNac.setEnabled(false);
        this.txtMail.setEnabled(false);
        this.txtPeso.setEnabled(false);
        this.txtOcupacion.setEnabled(false);
        this.txtTelefono.setEnabled(false);
        this.radiobtnImangen.setEnabled(false);
        this.radiobtnDatos.setEnabled(false);
        
        txtPaciente.setCaretPosition(0);
        txtDirecion.setCaretPosition(0);
        txtMail.setCaretPosition(0);
        txtOcupacion.setCaretPosition(0);
    }

    private void createAndShowGUI(){
        img=new JLabel();
        img.setPreferredSize(new Dimension(230,300));
        jf.setAccessory(img);
        jf.setAcceptAllFileFilterUsed(false);
        jf.addPropertyChangeListener((final PropertyChangeEvent pe) -> {
            SwingWorker<Image,Void> worker=new SwingWorker<Image,Void>(){
                @Override
                protected Image doInBackground(){
                    if(pe.getPropertyName().equals(JFileChooser.SELECTED_FILE_CHANGED_PROPERTY)){
                        File f=jf.getSelectedFile();
                        try{
                            FileInputStream fin=new FileInputStream(f);
                            BufferedImage bim=ImageIO.read(fin);
                            return bim.getScaledInstance(230,300,BufferedImage.SCALE_SMOOTH);
                        }catch(IOException e){
                            JOptionPane.showMessageDialog(null, "Error: "+ e);
                        }
                    }
                    return null;
                }
                @Override
                protected void done(){
                    try{
                        Image i=get(1L,TimeUnit.NANOSECONDS);
                        if(i==null) return;
                        img.setIcon(new ImageIcon(i));
                    }catch(InterruptedException | ExecutionException | TimeoutException e){
                        //img.setText("Se presentó un error "+e);
                    }
                }
            };
            worker.execute();
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel43 = new javax.swing.JLabel();
        txtIdEnfermeros = new javax.swing.JTextField();
        rbtnGrupo1 = new javax.swing.ButtonGroup();
        lblFoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtPaciente = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtDirecion = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtOcupacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jpcFechaNac = new org.jdesktop.swingx.JXDatePicker();
        txtLoginMed = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        radiobtnImangen = new javax.swing.JRadioButton();
        radiobtnDatos = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cmbListar = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtIdEnfermero = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCamara = new javax.swing.JButton();
        btnSubirFoto = new javax.swing.JButton();
        txtCategoria = new javax.swing.JTextField();
        txtCategoriaPaciente = new javax.swing.JTextField();

        jLabel43.setText("ID");

        txtIdEnfermeros.setEditable(false);
        txtIdEnfermeros.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdEnfermeros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbtnGrupo1.add(radiobtnImangen);
        rbtnGrupo1.add(radiobtnDatos);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Modificar Paciente");
        setResizable(false);

        lblFoto.setBackground(new java.awt.Color(153, 153, 153));
        lblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));
        jPanel1.setEnabled(false);

        jLabel2.setText("Cédula");

        jLabel3.setText("Paciente");

        jLabel5.setText("Edad");

        jLabel6.setText("Sexo");

        jLabel7.setText("Estatura");

        jLabel8.setText("Dirección");

        jLabel9.setText("Fecha de Nacimiento");

        jLabel10.setText("E-mail");

        jLabel11.setText("Peso");

        jLabel12.setText("Ocupación");

        jLabel13.setText("Teléfono");

        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        txtPaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPacienteFocusLost(evt);
            }
        });

        txtEdad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });

        txtDirecion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDirecion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDirecionFocusLost(evt);
            }
        });

        txtMail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMail.setAutoscrolls(false);
        txtMail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailFocusLost(evt);
            }
        });

        txtPeso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPeso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });

        txtOcupacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtOcupacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtOcupacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtOcupacionFocusLost(evt);
            }
        });

        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtEstatura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEstatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEstatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstaturaKeyTyped(evt);
            }
        });

        txtSexo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSexo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setText("kg");

        jLabel16.setText("Ej: 1.60");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)
                        .addGap(96, 96, 96)
                        .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGap(79, 79, 79)
                        .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(36, 36, 36)
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel14)
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(49, 49, 49)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(35, 35, 35)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jpcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtLoginMed.setEditable(false);
        txtLoginMed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLoginMed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCodigo.setEditable(false);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo.setText("Nº Historia Clínica");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        radiobtnImangen.setText("Cambiar Imagen");
        radiobtnImangen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnImangenMouseClicked(evt);
            }
        });

        radiobtnDatos.setText("Cambiar Datos");
        radiobtnDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radiobtnDatosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radiobtnDatos)
                    .addComponent(radiobtnImangen))
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobtnImangen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobtnDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        cmbListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Paciente", "Cédula" }));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
        });
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel15.setText("Buscar por:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addGap(277, 277, 277))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("ID");

        txtIdEnfermero.setEditable(false);
        txtIdEnfermero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIdEnfermero.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Bienvenido");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/camera.png"))); // NOI18N
        btnCamara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamaraActionPerformed(evt);
            }
        });

        btnSubirFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/upload.png"))); // NOI18N
        btnSubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCamara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnSubirFoto)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubirFoto)
                    .addComponent(btnCamara))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCategoriaPaciente.setEditable(false);
        txtCategoriaPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoriaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoginMed)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCategoriaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(463, 463, 463)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel45))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdEnfermero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoginMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitulo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCategoriaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarTabla() throws IOException{
        Conexion con = new Conexion();
        con.conectar();
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Paciente");
        modelo.addColumn("Cedula");
        modelo.addColumn("Telefono");
        modelo.addColumn("Edad");
        modelo.addColumn("Sexo");
        modelo.addColumn("Dirección");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Mail");
        modelo.addColumn("Estatura");
        modelo.addColumn("Peso");
        modelo.addColumn("Ocupación");
        modelo.addColumn("Foto");
        modelo.addColumn("Categoria");
        
        java.util.List<HistoriaClinica> lst = new ArrayList<>();
        HistoriaClinicaImp dao = new HistoriaClinicaImp();
        
        try {            
            lst = dao.obtener();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar los datos "+e,
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
        }
        
        for(HistoriaClinica exp:lst){
           modelo.addRow(new Object[]{
               exp.getCodigo(), 
               exp.getPaciente(),
               exp.getCedula(),
               exp.getTelefono(),
               exp.getEdad(),
               exp.getSexo(),
               exp.getDireccion(),
               exp.getFecha_nacimiento(),
               exp.getMail(),
               exp.getEstatura(),
               exp.getPeso(),
               exp.getOcupacion(),
               exp.getImagen(),
               exp.getCategoria(),
           });        
        }
        tabla.setModel(modelo);
        modelo.fireTableDataChanged();
        
        tabla.getColumnModel().getColumn(12).setMaxWidth(0);
        tabla.getColumnModel().getColumn(12).setMinWidth(0);
        tabla.getColumnModel().getColumn(12).setPreferredWidth(0);
        
        tabla.getColumnModel().getColumn(13).setMaxWidth(0);
        tabla.getColumnModel().getColumn(13).setMinWidth(0);
        tabla.getColumnModel().getColumn(13).setPreferredWidth(0);
    }
    
    public void ordenarTabla(){
        TableRowSorter<TableModel> ordenar = new TableRowSorter<>(modelo);
        tabla.setRowSorter(ordenar);
    }
    
    public void filtro() {
        int columnaABuscar = 0;
        if (cmbListar.getSelectedItem().equals("Código")) {
            columnaABuscar = 0;
        }
        if (cmbListar.getSelectedItem() == "Paciente") {
            columnaABuscar = 1;
        }
        if (cmbListar.getSelectedItem() == "Cédula") {
            columnaABuscar = 2;
        }
        String replace = txtBusqueda.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tabla.setRowSorter(trsFiltro);
    }
    
    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
        if (txtCedula.getText().length() == 10)  
             evt.consume();
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPacienteFocusLost
        txtPaciente.setCaretPosition(0);
    }//GEN-LAST:event_txtPacienteFocusLost

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtDirecionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDirecionFocusLost
        txtDirecion.setCaretPosition(0);
    }//GEN-LAST:event_txtDirecionFocusLost

    private void txtMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailFocusLost
        txtMail.setCaretPosition(0);
    }//GEN-LAST:event_txtMailFocusLost

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtPesoKeyTyped

    private void txtOcupacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOcupacionFocusLost
        txtOcupacion.setCaretPosition(0);
    }//GEN-LAST:event_txtOcupacionFocusLost

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0'};
        int b=0;
        for(int i=0;i<=9;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtEstaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstaturaKeyTyped
        char []p={'1','2','3','4','5','6','7','8','9','0','.'};
        int b=0;
        for(int i=0;i<=10;i++){
            if (p[i]==evt.getKeyChar()){
                b=1;
            }
        }
        if(b==0){
            evt.consume();
        }
    }//GEN-LAST:event_txtEstaturaKeyTyped

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setToolTipText("Guardar");
    }//GEN-LAST:event_btnGuardarMouseEntered

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(radiobtnImangen.isSelected()==false&&radiobtnDatos.isSelected()==false){
                JOptionPane.showMessageDialog(this, "No ha seleccionado una opción",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                if(radiobtnImangen.isSelected()){
                    if("camara".equals(botones)){
                        try{
                            String sql="UPDATE public.\"historia clinica\"\n" +
                            "   SET foto=? WHERE codigo="+Integer.parseInt(txtCodigo.getText());

                            try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                                ps.setBinaryStream(1, frmCamaraModificarPac.fin, frmCamaraModificarPac.longitudBytes);
                                ps.execute();
                                ps.close();
                            } catch (IOException ex) {
                                Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            JOptionPane.showMessageDialog(this, "Datos guardados correctamente...",
                                "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                        }catch(SQLException | NumberFormatException | HeadlessException x){
                                JOptionPane.showMessageDialog(rootPane, "Hubo un problema al guardar la información "+x);
                        }finally {
                            con.desconectar();
                        }
                    }else{
                        if("subir".equals(botones)){
                            try{
                                String sql="UPDATE public.\"historia clinica\"\n" +
                                "   SET foto=? WHERE codigo="+Integer.parseInt(txtCodigo.getText());

                                try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                                    ps.setBinaryStream(1, fis, longitudBytes);
                                    ps.execute();
                                    ps.close();
                                } catch (IOException ex) {
                                    Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                JOptionPane.showMessageDialog(this, "Datos guardados correctamente...",
                                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                            }catch(SQLException | NumberFormatException | HeadlessException x){
                                        JOptionPane.showMessageDialog(rootPane, "Hubo un problema al guardar la información "+x);
                            }finally {
                                con.desconectar();
                            }
                        }else{
                            if(btnCamara.isSelected()==false&&btnSubirFoto.isSelected()==false){
                                JOptionPane.showMessageDialog(this, "Debe escoger o tomar una foto",
                            "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                    }
                }
                if(radiobtnDatos.isSelected()){
                    try{
                        String sql="UPDATE public.\"historia clinica\"\n" +
                        "   SET paciente=?, cedula=?, telefono=?, edad=?, \n" +
                        "       sexo=?, direccion=?, \"fecha de nacimiento\"=?, mail=?, estatura=?, \n" +
                        "       peso=?, ocupacion=?, enfermero=? WHERE codigo="+Integer.parseInt(txtCodigo.getText());

                        try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                            ps.setString(1, txtPaciente.getText());
                            ps.setString(2, txtCedula.getText());
                            ps.setString(3, txtTelefono.getText());
                            ps.setInt(4, Integer.parseInt(txtEdad.getText()));
                            ps.setString(5, txtSexo.getText());
                            ps.setString(6, txtDirecion.getText());
                            ps.setDate(7, new java.sql.Date(jpcFechaNac.getDate().getTime()));
                            ps.setString(8, txtMail.getText());
                            ps.setDouble(9, Double.parseDouble(txtEstatura.getText()));
                            ps.setDouble(10, Double.parseDouble(txtPeso.getText()));
                            ps.setString(11, txtOcupacion.getText());
                            ps.setInt(12, Integer.parseInt(txtIdEnfermero.getText()));
                            ps.execute();
                            ps.close();
                        } catch (IOException ex) {
                            Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(this, "Datos guardados correctamente...",
                            "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
                    }catch(SQLException | NumberFormatException | HeadlessException x){
                        JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                    }finally {
                        con.desconectar();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void radiobtnImangenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnImangenMouseClicked
        btnSubirFoto.setEnabled(true);
        btnCamara.setEnabled(true);
        txtCedula.setEnabled(false);
        txtPaciente.setEnabled(false);
        txtEdad.setEnabled(false);
        txtSexo.setEnabled(false);
        txtEstatura.setEnabled(false);
        txtDirecion.setEnabled(false);
        jpcFechaNac.setEnabled(false);
        txtMail.setEnabled(false);
        txtPeso.setEnabled(false);
        txtOcupacion.setEnabled(false);
        txtTelefono.setEnabled(false);
    }//GEN-LAST:event_radiobtnImangenMouseClicked

    private void radiobtnDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radiobtnDatosMouseClicked
        btnSubirFoto.setEnabled(false);
        btnCamara.setEnabled(false);
        txtCedula.setEnabled(true);
        txtPaciente.setEnabled(true);
        txtEdad.setEnabled(true);
        txtSexo.setEnabled(true);
        txtEstatura.setEnabled(true);
        txtDirecion.setEnabled(true);
        jpcFechaNac.setEnabled(true);
        txtMail.setEnabled(true);
        txtPeso.setEnabled(true);
        txtOcupacion.setEnabled(true);
        txtTelefono.setEnabled(true);
    }//GEN-LAST:event_radiobtnDatosMouseClicked

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int selectedRowIndex = tabla.rowAtPoint(evt.getPoint());
        txtCodigo.setText(tabla.getValueAt(selectedRowIndex, 0).toString());
        txtPaciente.setText(tabla.getValueAt(selectedRowIndex, 1).toString());
        txtCedula.setText(tabla.getValueAt(selectedRowIndex, 2).toString());
        txtTelefono.setText(tabla.getValueAt(selectedRowIndex, 3).toString());
        txtEdad.setText(tabla.getValueAt(selectedRowIndex, 4).toString());
        txtSexo.setText(tabla.getValueAt(selectedRowIndex, 5).toString());
        txtDirecion.setText(tabla.getValueAt(selectedRowIndex, 6).toString());
        jpcFechaNac.setDate(java.sql.Date.valueOf(tabla.getValueAt(selectedRowIndex, 7).toString()));
        txtMail.setText(tabla.getValueAt(selectedRowIndex, 8).toString());
        txtEstatura.setText(tabla.getValueAt(selectedRowIndex, 9).toString());
        txtPeso.setText(tabla.getValueAt(selectedRowIndex, 10).toString());
        txtOcupacion.setText(tabla.getValueAt(selectedRowIndex, 11).toString());
        byte[] byteArray = (byte[]) tabla.getValueAt(selectedRowIndex, 12);
        if(byteArray ==null){
            lblFoto.setIcon(null);
            lblFoto.setText("                  SIN IMAGEN");
        }else{
            ByteArrayInputStream bais = new ByteArrayInputStream(byteArray);
            BufferedImage bImg;
            try {
                lblFoto.setText("");
                bImg = ImageIO.read(bais);
                bImg= Scalr.resize(bImg, Scalr.Method.SPEED, Scalr.Mode.FIT_EXACT, 175, 223); 
                lblFoto.setIcon(new javax.swing.ImageIcon(bImg));
                bais.close();
            } catch (IOException ex) {
                Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtCategoriaPaciente.setText(tabla.getValueAt(selectedRowIndex, 13).toString());
        this.radiobtnImangen.setEnabled(true);
        this.radiobtnDatos.setEnabled(true);
        
        txtDirecion.setCaretPosition(0);
        txtPaciente.setCaretPosition(0);
    }//GEN-LAST:event_tablaMouseClicked

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        txtBusqueda.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = txtBusqueda.getText();
                txtBusqueda.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tabla.getModel());
        tabla.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered
        btnRefresh.setToolTipText("Actualizar tabla");
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Conexion con = new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmModificarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelo.setRowCount( 0 );
        
        java.util.List<HistoriaClinica> lst = new ArrayList<>();
        HistoriaClinicaImp dao = new HistoriaClinicaImp();
        
        try {            
            lst = dao.obtener();            
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar los datos "+e,
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
        }
        
        for(HistoriaClinica exp:lst){
           modelo.addRow(new Object[]{
               exp.getCodigo(), 
               exp.getPaciente(),
               exp.getCedula(),
               exp.getTelefono(),
               exp.getEdad(),
               exp.getSexo(),
               exp.getDireccion(),
               exp.getFecha_nacimiento(),
               exp.getMail(),
               exp.getEstatura(),
               exp.getPeso(),
               exp.getOcupacion(),
               exp.getImagen(),
           });        
        }
        tabla.setModel(modelo);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCamaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamaraActionPerformed
        frmCamaraModificarPac web = new frmCamaraModificarPac();
        web.run();
        botones="camara";
    }//GEN-LAST:event_btnCamaraActionPerformed

    private void btnSubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirFotoActionPerformed
        int resultado;
        botones="subir";
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        jf.setFileFilter(filtro);
        Frame f = new Frame();
        f.setTitle("Seleccione una imagen");
        f.setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        resultado= jf.showOpenDialog(f);
        if (JFileChooser.APPROVE_OPTION == resultado){
            try{
                fis=new FileInputStream(jf.getSelectedFile());
                this.longitudBytes=(int)jf.getSelectedFile().length();
                try{
                    lblFoto.setText("");
                    Image icono=ImageIO.read(jf.getSelectedFile()).getScaledInstance
                    (lblFoto.getWidth(),lblFoto.getHeight(),Image.SCALE_FAST);
                    lblFoto.setIcon(new ImageIcon(icono));
                    lblFoto.updateUI();
                }catch(IOException ex){
                    JOptionPane.showMessageDialog(rootPane, "imagen: "+ex);
                }
            }catch(HeadlessException | FileNotFoundException ex){
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);
            }
        }
    }//GEN-LAST:event_btnSubirFotoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCamara;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSubirFoto;
    private javax.swing.JComboBox<String> cmbListar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXDatePicker jpcFechaNac;
    public static javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radiobtnDatos;
    private javax.swing.JRadioButton radiobtnImangen;
    private javax.swing.ButtonGroup rbtnGrupo1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBusqueda;
    public static javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCategoriaPaciente;
    public static javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtDirecion;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtEstatura;
    public static javax.swing.JTextField txtIdEnfermero;
    public static javax.swing.JTextField txtIdEnfermeros;
    private javax.swing.JTextField txtLoginMed;
    public javax.swing.JTextField txtMail;
    public javax.swing.JTextField txtOcupacion;
    public javax.swing.JTextField txtPaciente;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
