/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ec.com.cebycam.vistas.Medico;
import ec.com.cebycam.accesodatos.Conexion;
import ec.com.cebycam.dao.impl.HistoriaClinicaImp;
import ec.com.cebycam.rnegocio.entidades.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.*;
import org.imgscalr.Scalr;

/**
 *
 * @author lufeb
 */

public final class frmAtencionPaciente extends javax.swing.JInternalFrame {
    JLabel img;
    JButton open;
    JFileChooser jf=new JFileChooser();
    TableRowSorter trsFiltro;
    DefaultTableModel modelo;
    
    public static String dato=null;
    public static int codigo;
    public static String categoria;
    Medicos medico;

    /**
     * Creates new form frmInsertarPaciente
     * @throws java.io.IOException
     */
    public frmAtencionPaciente() throws IOException {
        initComponents();
        frmAtencionPaciente.txtAtencionMedico.setText(dato);
        this.txtCodigoMedico.setText(String.valueOf(codigo));
        frmAtencionPaciente.txtCategoriaDoc.setText(categoria);
        cargarTabla();
        ordenarTabla();
        JRootPane boton = SwingUtilities.getRootPane(btnGuardar); 
        boton.setDefaultButton(btnGuardar);
    }
    
    public boolean editarCeldas(int row, int column) {
	return false;
    }
    
    public void date(){
        java.util.Date date=new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String Format= format.format(date);
        this.txtFechaAtencion.setText(Format);
        java.sql.Date.valueOf(Format);
    }
    
    public void tiempo(){
        java.util.Date hora=new java.util.Date(System.currentTimeMillis());
        SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss");
        String Format= format.format(hora);
        Time.valueOf(Format);
        frmAtencionPaciente.txtHoraAtencion.setText(Format);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFoto = new javax.swing.JLabel();
        txtAtencionMedico = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtPaciente = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtDirecion = new javax.swing.JTextField();
        txtFechaNac = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        txtOcupacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtCodigoPac = new javax.swing.JTextField();
        txtCategoriaPac = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtIndicaciones = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnAtencionPrevia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSignosVitalesAtencion = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cmbListar = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtCodigoMedico = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFechaAtencion = new javax.swing.JTextField();
        txtHoraAtencion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtPrescripciones = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtDiagnosticoAtencion = new javax.swing.JTextField();
        txtCategoriaDoc = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("CEBYCAM-CES :: Atención");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png"))); // NOI18N

        lblFoto.setBackground(new java.awt.Color(153, 153, 153));
        lblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAtencionMedico.setEditable(false);
        txtAtencionMedico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAtencionMedico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Paciente"));
        jPanel1.setEnabled(false);

        jLabel2.setText("Cédula");

        jLabel3.setText("Paciente");

        jLabel5.setText("Edad");

        jLabel6.setText("Sexo");

        jLabel7.setText("Estatura");

        jLabel8.setText("Dirección");

        jLabel9.setText("Fecha de Nacimiento");

        jLabel10.setText("E-mail");

        jLabel11.setText("Peso");

        jLabel12.setText("Ocupación");

        jLabel13.setText("Teléfono");

        txtCedula.setEditable(false);
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCedula.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPaciente.setEditable(false);
        txtPaciente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPacienteFocusGained(evt);
            }
        });

        txtEdad.setEditable(false);
        txtEdad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEdad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDirecion.setEditable(false);
        txtDirecion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtFechaNac.setEditable(false);
        txtFechaNac.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFechaNac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtMail.setEditable(false);
        txtMail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMail.setAutoscrolls(false);
        txtMail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtPeso.setEditable(false);
        txtPeso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPeso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtOcupacion.setEditable(false);
        txtOcupacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtOcupacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTelefono.setEditable(false);
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtEstatura.setEditable(false);
        txtEstatura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEstatura.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSexo.setEditable(false);
        txtSexo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSexo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setText("AA-MM-DD");

        jLabel15.setText("kg");

        jLabel17.setText("Ej: 1.60");

        lblTitulo.setText("H.Clínica");

        txtCodigoPac.setEditable(false);
        txtCodigoPac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCategoriaPac.setEditable(false);
        txtCategoriaPac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoriaPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(36, 36, 36)
                                .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTitulo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(92, 92, 92)
                                .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel13)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCategoriaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel6)
                                .addGap(111, 111, 111)
                                .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel10)
                                .addGap(63, 63, 63)
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel7)
                                .addGap(94, 94, 94)
                                .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel17)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel12)
                                .addGap(41, 41, 41)
                                .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7))
                    .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel14)
                        .addComponent(lblTitulo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCategoriaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCedula.getAccessibleContext().setAccessibleParent(txtCedula);
        txtPaciente.getAccessibleContext().setAccessibleParent(txtPaciente);
        txtSexo.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Indicaciones"));

        jtxtIndicaciones.setColumns(20);
        jtxtIndicaciones.setLineWrap(true);
        jtxtIndicaciones.setRows(5);
        jtxtIndicaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtIndicacionesKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtxtIndicaciones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas"));

        btnAtencionPrevia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/receta_256px-0.png"))); // NOI18N
        btnAtencionPrevia.setText("Atenciones Previas");
        btnAtencionPrevia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtencionPreviaActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/atencion-0.png"))); // NOI18N
        jButton1.setText("Fotografías");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSignosVitalesAtencion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/paciente-0.png"))); // NOI18N
        btnSignosVitalesAtencion.setText("Signos Vitales");
        btnSignosVitalesAtencion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSignosVitalesAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignosVitalesAtencionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAtencionPrevia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnSignosVitalesAtencion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSignosVitalesAtencion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtencionPrevia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/guardar_256px-2.png"))); // NOI18N
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacientes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel16.setText("Buscar por:");

        cmbListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H.Clinica", "Paciente", "Cédula" }));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshMouseEntered(evt);
            }
        });
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabla.setAutoscrolls(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(cmbListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtCodigoMedico.setEditable(false);
        txtCodigoMedico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoMedico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Bienvenido");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("ID");
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha.setText("Fecha:");

        txtFechaAtencion.setEditable(false);
        txtFechaAtencion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFechaAtencion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtHoraAtencion.setEditable(false);
        txtHoraAtencion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHoraAtencion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Hora:");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Prescripciones"));

        jtxtPrescripciones.setColumns(20);
        jtxtPrescripciones.setLineWrap(true);
        jtxtPrescripciones.setRows(5);
        jtxtPrescripciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPrescripcionesKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jtxtPrescripciones);
        jtxtPrescripciones.getAccessibleContext().setAccessibleParent(jScrollPane1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Diagnóstico:");

        txtDiagnosticoAtencion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiagnosticoAtencionFocusLost(evt);
            }
        });

        txtCategoriaDoc.setEditable(false);
        txtCategoriaDoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoriaDoc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHoraAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiagnosticoAtencion))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(txtAtencionMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCategoriaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtencionMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(txtFechaAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtHoraAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtDiagnosticoAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    File fichero;
        
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "CEBYCAM-CES",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(jtxtIndicaciones.getText().equals("")||txtCodigoPac.getText().equals("")||txtCodigoMedico.getText().equals("")
                    ||jtxtPrescripciones.getText().equals("")||txtDiagnosticoAtencion.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            }else{
                try{
                    String sql="SELECT insertarAtencion(?, ?, ?, ?, ?, ?, ?);";

                    try (PreparedStatement ps = con.conectar().prepareStatement(sql)) {
                        ps.setString(1, jtxtIndicaciones.getText());
                        ps.setInt(2, Integer.parseInt(txtCodigoPac.getText()));
                        ps.setDate(3, java.sql.Date.valueOf(txtFechaAtencion.getText()));
                        ps.setInt(4, Integer.parseInt(txtCodigoMedico.getText()));
                        ps.setTime(5, Time.valueOf(txtHoraAtencion.getText()));
                        ps.setString(6, jtxtPrescripciones.getText());
                        ps.setString(7, txtDiagnosticoAtencion.getText());
                        ps.execute();
                        ps.close();
                    } catch (IOException ex) {
                        Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
                    
                    jtxtIndicaciones.setText("");
                    jtxtPrescripciones.setText("");
                    txtDiagnosticoAtencion.setText("");
                }catch(SQLException | NumberFormatException | HeadlessException x){
                    JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos "+x);
                }finally {
                    con.desconectar();
                }
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setToolTipText("Guardar"); 
    }//GEN-LAST:event_btnGuardarMouseEntered
   
    public void ordenarTabla(){
        TableRowSorter<TableModel> ordenar = new TableRowSorter<>(modelo);
        tabla.setRowSorter(ordenar);
    }
    
    public void cargarTabla() throws IOException{
        Conexion con = new Conexion();
        con.conectar();
        
        modelo = new DefaultTableModel();
        modelo.addColumn("H.Clinica");
        modelo.addColumn("Paciente");
        modelo.addColumn("Cedula");
        modelo.addColumn("Telefono");
        modelo.addColumn("Edad");
        modelo.addColumn("Sexo");
        modelo.addColumn("Dirección");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Mail");
        modelo.addColumn("Estatura");
        modelo.addColumn("Peso");
        modelo.addColumn("Ocupación");
        modelo.addColumn("Foto");
        modelo.addColumn("Categoria");
        
        java.util.List<HistoriaClinica> lst = new ArrayList<>();
        HistoriaClinicaImp dao = new HistoriaClinicaImp();
        
        try {            
            lst = dao.obtener();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar los datos "+e,
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
        }
        
        for(HistoriaClinica exp:lst){
           modelo.addRow(new Object[]{
               exp.getCodigo(), 
               exp.getPaciente(),
               exp.getCedula(),
               exp.getTelefono(),
               exp.getEdad(),
               exp.getSexo(),
               exp.getDireccion(),
               exp.getFecha_nacimiento(),
               exp.getMail(),
               exp.getEstatura(),
               exp.getPeso(),
               exp.getOcupacion(),
               exp.getImagen(),
               exp.getCategoria(),
           });        
        }
        tabla.setModel(modelo);
        modelo.fireTableDataChanged();
        
        
        tabla.getColumnModel().getColumn(12).setMaxWidth(0);
        tabla.getColumnModel().getColumn(12).setMinWidth(0);
        tabla.getColumnModel().getColumn(12).setPreferredWidth(0);
        
        tabla.getColumnModel().getColumn(13).setMaxWidth(0);
        tabla.getColumnModel().getColumn(13).setMinWidth(0);
        tabla.getColumnModel().getColumn(13).setPreferredWidth(0);
    }
       
    
    private void txtPacienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPacienteFocusGained
        txtPaciente.setCaretPosition(0);
    }//GEN-LAST:event_txtPacienteFocusGained
    
    public void filtro() {
        int columnaABuscar = 0;
        if (cmbListar.getSelectedItem().equals("H.Clinica")) {
            columnaABuscar = 0;
        }
        if (cmbListar.getSelectedItem() == "Paciente") {
            columnaABuscar = 1;
        }
        if (cmbListar.getSelectedItem() == "Cédula") {
            columnaABuscar = 2;
        }
        String replace = txtBusqueda.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tabla.setRowSorter(trsFiltro);
    }
    
    private void btnAtencionPreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtencionPreviaActionPerformed
        frmAtencionPrevia frm = null;
        try {
            frm = new frmAtencionPrevia();
        } catch (IOException ex) {
            Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        frm.setVisible(true);
    }//GEN-LAST:event_btnAtencionPreviaActionPerformed

    private void jtxtIndicacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtIndicacionesKeyTyped
        if(txtCodigoPac.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe escoger un paciente de la tabla",
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume(); 
            }
        }
    }//GEN-LAST:event_jtxtIndicacionesKeyTyped

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        txtBusqueda.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusqueda.getText());
                txtBusqueda.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tabla.getModel());
        tabla.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Conexion con = new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelo.setRowCount( 0 );
        
        java.util.List<HistoriaClinica> lst = new ArrayList<>();
        HistoriaClinicaImp dao = new HistoriaClinicaImp();
        
        try {            
            lst = dao.obtener();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al procesar los datos "+e,
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
        }
        
        for(HistoriaClinica exp:lst){
           modelo.addRow(new Object[]{
               exp.getCodigo(), 
               exp.getPaciente(),
               exp.getCedula(),
               exp.getTelefono(),
               exp.getEdad(),
               exp.getSexo(),
               exp.getDireccion(),
               exp.getFecha_nacimiento(),
               exp.getMail(),
               exp.getEstatura(),
               exp.getPeso(),
               exp.getOcupacion(),
               exp.getImagen(),
               exp.getCategoria(),
           });        
        }
        tabla.setModel(modelo);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRefreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseEntered
        btnRefresh.setToolTipText("Actualizar tabla");
    }//GEN-LAST:event_btnRefreshMouseEntered

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        int selectedRowIndex = tabla.rowAtPoint(evt.getPoint());
        txtCodigoPac.setText(tabla.getValueAt(selectedRowIndex, 0).toString());
        txtPaciente.setText(tabla.getValueAt(selectedRowIndex, 1).toString());
        txtCedula.setText(tabla.getValueAt(selectedRowIndex, 2).toString());
        txtTelefono.setText(tabla.getValueAt(selectedRowIndex, 3).toString());
        txtEdad.setText(tabla.getValueAt(selectedRowIndex, 4).toString());
        txtSexo.setText(tabla.getValueAt(selectedRowIndex, 5).toString());
        txtDirecion.setText(tabla.getValueAt(selectedRowIndex, 6).toString());
        txtFechaNac.setText(tabla.getValueAt(selectedRowIndex, 7).toString());
        txtMail.setText(tabla.getValueAt(selectedRowIndex, 8).toString());
        txtEstatura.setText(tabla.getValueAt(selectedRowIndex, 9).toString());
        txtPeso.setText(tabla.getValueAt(selectedRowIndex, 10).toString());
        txtOcupacion.setText(tabla.getValueAt(selectedRowIndex, 11).toString());
        byte[] byteArray = (byte[]) tabla.getValueAt(selectedRowIndex, 12);

        if(byteArray ==null){
            lblFoto.setIcon(null);
            lblFoto.setText("                  SIN IMAGEN");
        }else{
            ByteArrayInputStream bais = new ByteArrayInputStream(byteArray);
            BufferedImage bImg;

            try {
                bImg = ImageIO.read(bais);
                bImg= Scalr.resize(bImg, Scalr.Method.SPEED, Scalr.Mode.FIT_EXACT, 175, 223); 
                lblFoto.setIcon(new javax.swing.ImageIcon(bImg));
                bais.close();
            } catch (IOException ex) {
                Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtCategoriaPac.setText(tabla.getValueAt(selectedRowIndex, 13).toString());
        date();
        tiempo();
        txtPaciente.setCaretPosition(0);
        txtDirecion.setCaretPosition(0);
        txtMail.setCaretPosition(0);
        txtOcupacion.setCaretPosition(0);
    }//GEN-LAST:event_tablaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmFotos frm = new frmFotos();
        frm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSignosVitalesAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignosVitalesAtencionActionPerformed
        frmConsultaSignosVitales consulta = null;
        try {
            consulta = new frmConsultaSignosVitales();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        consulta.setVisible(true);
    }//GEN-LAST:event_btnSignosVitalesAtencionActionPerformed

    private void jtxtPrescripcionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrescripcionesKeyTyped
        if(txtCodigoPac.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe escoger un paciente de la tabla",
                        "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
            char c = evt.getKeyChar();
            if (!Character.isDigit(c)) {
                evt.consume(); 
            }
        }
    }//GEN-LAST:event_jtxtPrescripcionesKeyTyped

    private void txtDiagnosticoAtencionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiagnosticoAtencionFocusLost
        txtDiagnosticoAtencion.setCaretPosition(0);
    }//GEN-LAST:event_txtDiagnosticoAtencionFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtencionPrevia;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSignosVitalesAtencion;
    private javax.swing.JComboBox<String> cmbListar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextArea jtxtIndicaciones;
    private javax.swing.JTextArea jtxtPrescripciones;
    private javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabla;
    public static javax.swing.JTextField txtAtencionMedico;
    private javax.swing.JTextField txtBusqueda;
    public static javax.swing.JTextField txtCategoriaDoc;
    private javax.swing.JTextField txtCategoriaPac;
    public static javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCodigoMedico;
    public javax.swing.JTextField txtCodigoPac;
    private javax.swing.JTextField txtDiagnosticoAtencion;
    public javax.swing.JTextField txtDirecion;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtEstatura;
    private javax.swing.JTextField txtFechaAtencion;
    public javax.swing.JTextField txtFechaNac;
    public static javax.swing.JTextField txtHoraAtencion;
    public javax.swing.JTextField txtMail;
    public javax.swing.JTextField txtOcupacion;
    public javax.swing.JTextField txtPaciente;
    public javax.swing.JTextField txtPeso;
    public javax.swing.JTextField txtSexo;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
