/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.cebycam.vistas.Medico;

import ec.com.cebycam.accesodatos.Conexion;
import ec.com.cebycam.vistas.Enfermeria.frmEnfermeria;
import static ec.com.cebycam.vistas.Medico.frmPrincipal.txtMedicoWelcome;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.sql.*;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.*;
import org.imgscalr.Scalr;

/**
 *
 * @author lufeb
 */
public final class frmConsultaSignosVitales extends javax.swing.JFrame {
    public static String nombreDoctor;
    DefaultTableModel modelo;
    TableRowSorter trsFiltro;
    /**
     * Creates new form frm
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public frmConsultaSignosVitales() throws SQLException, IOException {
        initComponents();
        cargarTabla();
        ordenarTabla();
        frmConsultaSignosVitales.txtDoctorLogin.setText(nombreDoctor);
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(frmEnfermeria.DISPOSE_ON_CLOSE);
        JRootPane boton = SwingUtilities.getRootPane(btnAceptar); 
        boton.setDefaultButton(btnAceptar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel44 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtNombrePac = new javax.swing.JTextField();
        txtCedulaPac = new javax.swing.JTextField();
        txtEdadPac = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtCodigoHistoria = new javax.swing.JTextField();
        lblFotoPac = new javax.swing.JLabel();
        txtCategoriaPaciente = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtHoraPac = new javax.swing.JTextField();
        txtTemperaturaPac = new javax.swing.JTextField();
        txtFrecuenciaCardiacaPac = new javax.swing.JTextField();
        txtSatO2Pac = new javax.swing.JTextField();
        txtPresionArtPac = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtAntecedentesPac = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        txtPacAlergias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPacSintomas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFechaPac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMedicoTratante = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPac = new javax.swing.JTable();
        btnActualizarPac = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        cmbListarPac = new javax.swing.JComboBox<>();
        txtBusquedaPac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAtendido = new javax.swing.JTextField();
        txtDoctorLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CEBYCAM-CES :: Signos Vitales");
        setResizable(false);

        jLabel44.setText("Bienvenido");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos del Paciente"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setText("Nombres:");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 217, -1, -1));

        jLabel33.setText("Cédula:");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 275, -1, -1));

        jLabel34.setText("Edad:");
        jPanel10.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 304, -1, -1));

        txtNombrePac.setEditable(false);
        txtNombrePac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(txtNombrePac, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 215, 149, -1));

        txtCedulaPac.setEditable(false);
        txtCedulaPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(txtCedulaPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 273, 148, -1));

        txtEdadPac.setEditable(false);
        txtEdadPac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(txtEdadPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 302, 148, -1));

        jLabel37.setText("Código H.Clínica");
        jPanel10.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 246, -1, -1));

        txtCodigoHistoria.setEditable(false);
        txtCodigoHistoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(txtCodigoHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 244, 120, -1));

        lblFotoPac.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.add(lblFotoPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 27, 130, 170));

        txtCategoriaPaciente.setEditable(false);
        txtCategoriaPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoriaPaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.add(txtCategoriaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 244, 23, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("SIGNOS VITALES");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Atención"));

        jLabel38.setText("Hora:");

        jLabel39.setText("Temperatura:");

        jLabel40.setText("Frecuencia Cardiaca:");

        jLabel41.setText("Saturación Oxígeno:");

        jLabel42.setText("Presión Arterial:");

        txtHoraPac.setEditable(false);

        txtTemperaturaPac.setEditable(false);

        txtFrecuenciaCardiacaPac.setEditable(false);

        txtSatO2Pac.setEditable(false);

        txtPresionArtPac.setEditable(false);

        jLabel35.setText("Antecedentes:");

        txtAntecedentesPac.setEditable(false);

        jLabel36.setText("Alergias:");

        txtPacAlergias.setEditable(false);

        jLabel1.setText("Sintomas");

        txtPacSintomas.setEditable(false);

        jLabel3.setText("Fecha");

        txtFechaPac.setEditable(false);
        txtFechaPac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Médico Tratante");

        txtMedicoTratante.setEditable(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel38)
                        .addGap(95, 95, 95)
                        .addComponent(txtHoraPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel39)
                        .addGap(56, 56, 56)
                        .addComponent(txtTemperaturaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel40)
                        .addGap(21, 21, 21)
                        .addComponent(txtFrecuenciaCardiacaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel41)
                        .addGap(24, 24, 24)
                        .addComponent(txtSatO2Pac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel42)
                        .addGap(45, 45, 45)
                        .addComponent(txtPresionArtPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(79, 79, 79)
                        .addComponent(txtPacSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel35)
                        .addGap(51, 51, 51)
                        .addComponent(txtAntecedentesPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel36)
                        .addGap(80, 80, 80)
                        .addComponent(txtPacAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(93, 93, 93)
                        .addComponent(txtFechaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMedicoTratante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel38))
                    .addComponent(txtHoraPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel39))
                    .addComponent(txtTemperaturaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel40))
                    .addComponent(txtFrecuenciaCardiacaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel41))
                    .addComponent(txtSatO2Pac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel42))
                    .addComponent(txtPresionArtPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtPacSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel35))
                    .addComponent(txtAntecedentesPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel36))
                    .addComponent(txtPacAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(txtFechaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMedicoTratante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Pacientes"));

        tablaPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPac.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaPac.setAutoscrolls(false);
        tablaPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPacMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaPac);

        btnActualizarPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/cebycam/imagenes/refresh-0.png"))); // NOI18N
        btnActualizarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPacActionPerformed(evt);
            }
        });

        jLabel45.setText("Buscar por:");

        cmbListarPac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H.Clinica", "Paciente", "Cédula", "Médico" }));

        txtBusquedaPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaPacKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbListarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusquedaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarPac, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusquedaPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbListarPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45)))
                    .addComponent(btnActualizarPac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Atendido por:");

        txtAtendido.setEditable(false);
        txtAtendido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAtendido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtDoctorLogin.setEditable(false);
        txtDoctorLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDoctorLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(574, 574, 574)
                        .addComponent(jLabel44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addComponent(txtDoctorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(btnAceptar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel44)
                .addGap(6, 6, 6)
                .addComponent(txtDoctorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel31)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarTabla() throws SQLException, IOException{
        Conexion con = new Conexion();
        con.conectar();
         ResultSet rs = null;
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Médico");
        modelo.addColumn("Atendido");
        modelo.addColumn("H.Clinica");
        modelo.addColumn("Paciente");
        modelo.addColumn("Cédula");
        modelo.addColumn("Edad");
        modelo.addColumn("Foto");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Temperatura");
        modelo.addColumn("Frec.Cardiaca");
        modelo.addColumn("Sat.Oxigeno");
        modelo.addColumn("Pres.Arterial");
        modelo.addColumn("Sintomas");
        modelo.addColumn("Antecedentes");
        modelo.addColumn("Alergias");
        modelo.addColumn("Categoria");
        
        try{
            String sql="SELECT \n" +
"\"signos_vitales\".medico, \n" +
"\"enfermeria\".nombre as \"enfermera\", \n" +
"\"historia_clinica\".codigo, \n" +
"\"historia_clinica\".paciente, \n" +
"\"historia_clinica\".cedula, \n" +
"\"historia_clinica\".edad, \n" +
"\"historia_clinica\".foto, \n" +
"\"signos_vitales\".fecha, \n" +
"\"signos_vitales\".hora, \n" +
"\"signos_vitales\".temperatura, \n" +
"\"signos_vitales\".\"frecuencia cardiaca\", \n" +
"\"signos_vitales\".saturacion, \n" +
"\"signos_vitales\".\"presion arterial\", \n" +
"\"signos_vitales\".sintomas, \n" +
"\"signos_vitales\".antecedentes, \n" +
"\"signos_vitales\".alergias, \n" +
"\"historia_clinica\".categoria \n" +
"FROM \n" +
"public.\"signos vitales\" signos_vitales inner join public.\"historia clinica\" historia_clinica on signos_vitales.\"paciente\"=historia_clinica.\"codigo\" inner join\n" +
"public.\"enfermeria\" enfermeria on signos_vitales.\"enfermero\"=enfermeria.\"codigo\"\n" +
"WHERE signos_vitales.\"medico\"='"+txtMedicoWelcome.getText()+"';";
            rs = con.ejecutarQuery(sql);
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        }finally {
            con.desconectar();
            rs.close();
        }
        
        tablaPac.setModel(modelo);
        modelo.fireTableDataChanged();
        
        tablaPac.getColumnModel().getColumn(6).setMaxWidth(0);
        tablaPac.getColumnModel().getColumn(6).setMinWidth(0);
        tablaPac.getColumnModel().getColumn(6).setPreferredWidth(0);
        
        tablaPac.getColumnModel().getColumn(16).setMaxWidth(0);
        tablaPac.getColumnModel().getColumn(16).setMinWidth(0);
        tablaPac.getColumnModel().getColumn(16).setPreferredWidth(0);
    }
    
    public void filtro() {
        int columnaABuscar = 0;
        if (cmbListarPac.getSelectedItem().equals("H.Clinica")) {
            columnaABuscar = 2;
        }
        if (cmbListarPac.getSelectedItem() == "Paciente") {
            columnaABuscar = 3;
        }
        if (cmbListarPac.getSelectedItem() == "Cédula") {
            columnaABuscar = 4;
        }
        if (cmbListarPac.getSelectedItem() == "Médico") {
            columnaABuscar = 0;
        }
        String replace = txtBusquedaPac.getText();
        replace = replace.replace("e", "(é)");
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i).*"+replace+".*", columnaABuscar));
        tablaPac.setRowSorter(trsFiltro);
    }
    
    public void ordenarTabla(){
        TableRowSorter<TableModel> ordenar = new TableRowSorter<>(modelo);
        tablaPac.setRowSorter(ordenar);
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void tablaPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPacMouseClicked
        int selectedRowIndex = tablaPac.rowAtPoint(evt.getPoint());
        txtMedicoTratante.setText(tablaPac.getValueAt(selectedRowIndex, 0).toString());
        txtAtendido.setText(tablaPac.getValueAt(selectedRowIndex, 1).toString());
        txtCodigoHistoria.setText(tablaPac.getValueAt(selectedRowIndex, 2).toString());
        txtNombrePac.setText(tablaPac.getValueAt(selectedRowIndex, 3).toString());
        txtCedulaPac.setText(tablaPac.getValueAt(selectedRowIndex, 4).toString());
        txtEdadPac.setText(tablaPac.getValueAt(selectedRowIndex, 5).toString());
        byte[] byteArray = (byte[]) tablaPac.getValueAt(selectedRowIndex, 6);
        if(byteArray ==null){
            lblFotoPac.setIcon(null);
            lblFotoPac.setText("            SIN IMAGEN");
        }else{
            ByteArrayInputStream bais = new ByteArrayInputStream(byteArray);
            BufferedImage bImg;

            try {
                bImg = ImageIO.read(bais);
                bImg= Scalr.resize(bImg, Scalr.Method.SPEED, Scalr.Mode.FIT_EXACT, 130, 170); 
                lblFotoPac.setIcon(new javax.swing.ImageIcon(bImg));
                bais.close();
            } catch (IOException ex) {
                Logger.getLogger(frmAtencionPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtFechaPac.setText(tablaPac.getValueAt(selectedRowIndex, 7).toString());
        txtHoraPac.setText(tablaPac.getValueAt(selectedRowIndex, 8).toString());
        txtTemperaturaPac.setText(tablaPac.getValueAt(selectedRowIndex, 9).toString());
        txtFrecuenciaCardiacaPac.setText(tablaPac.getValueAt(selectedRowIndex, 10).toString());
        txtSatO2Pac.setText(tablaPac.getValueAt(selectedRowIndex, 11).toString());
        txtPresionArtPac.setText(tablaPac.getValueAt(selectedRowIndex, 12).toString());
        txtPacSintomas.setText(tablaPac.getValueAt(selectedRowIndex, 13).toString());
        txtAntecedentesPac.setText(tablaPac.getValueAt(selectedRowIndex, 14).toString());
        txtPacAlergias.setText(tablaPac.getValueAt(selectedRowIndex, 15).toString());
        txtCategoriaPaciente.setText(tablaPac.getValueAt(selectedRowIndex, 16).toString());
        
        
    }//GEN-LAST:event_tablaPacMouseClicked

    private void btnActualizarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPacActionPerformed
        Conexion con = new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmConsultaSignosVitales.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet rs = null;
        modelo.setRowCount( 0 );
        
        try{
            String sql="SELECT \n" +
"\"signos_vitales\".medico, \n" +
"\"enfermeria\".nombre as \"enfermera\", \n" +
"\"historia_clinica\".codigo, \n" +
"\"historia_clinica\".paciente, \n" +
"\"historia_clinica\".cedula, \n" +
"\"historia_clinica\".edad, \n" +
"\"historia_clinica\".foto, \n" +
"\"signos_vitales\".fecha, \n" +
"\"signos_vitales\".hora, \n" +
"\"signos_vitales\".temperatura, \n" +
"\"signos_vitales\".\"frecuencia cardiaca\", \n" +
"\"signos_vitales\".saturacion, \n" +
"\"signos_vitales\".\"presion arterial\", \n" +
"\"signos_vitales\".sintomas, \n" +
"\"signos_vitales\".antecedentes, \n" +
"\"signos_vitales\".alergias, \n" +
"\"historia_clinica\".categoria \n" +
"FROM \n" +
"public.\"signos vitales\" signos_vitales inner join public.\"historia clinica\" historia_clinica on signos_vitales.\"paciente\"=historia_clinica.\"codigo\" inner join\n" +
"public.\"enfermeria\" enfermeria on signos_vitales.\"enfermero\"=enfermeria.\"codigo\"\n" +
"WHERE signos_vitales.\"medico\"='"+txtDoctorLogin.getText()+"';";
            rs = con.ejecutarQuery(sql);
                ResultSetMetaData md = rs.getMetaData();
                int columnCount = md.getColumnCount();
                String[] cols = new String[columnCount];
                for (int i=1;i<= columnCount;i++){
                    cols[i-1] = md.getColumnName(i);
                }
                while (rs.next()){
                    Object[] row = new Object[columnCount];
                    for (int i = 1 ; i <= columnCount ; i++){
                        row[i-1] = rs.getObject(i);
                    }
                    modelo.addRow(row);
                }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error "+e,
                    "CEBYCAM-CES", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmConsultaSignosVitales.class.getName()).log(Level.SEVERE, null, ex);
        }finally {
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmConsultaSignosVitales.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        tablaPac.setModel(modelo);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_btnActualizarPacActionPerformed

    private void txtBusquedaPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaPacKeyTyped
        txtBusquedaPac.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtBusquedaPac.getText());
                txtBusquedaPac.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaPac.getModel());
        tablaPac.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtBusquedaPacKeyTyped
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnActualizarPac;
    private javax.swing.JComboBox<String> cmbListarPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblFotoPac;
    private javax.swing.JTable tablaPac;
    public static javax.swing.JTextField txtAntecedentesPac;
    private javax.swing.JTextField txtAtendido;
    private javax.swing.JTextField txtBusquedaPac;
    private javax.swing.JTextField txtCategoriaPaciente;
    public static javax.swing.JTextField txtCedulaPac;
    public static javax.swing.JTextField txtCodigoHistoria;
    public static javax.swing.JTextField txtDoctorLogin;
    public static javax.swing.JTextField txtEdadPac;
    private javax.swing.JTextField txtFechaPac;
    public static javax.swing.JTextField txtFrecuenciaCardiacaPac;
    public static javax.swing.JTextField txtHoraPac;
    private javax.swing.JTextField txtMedicoTratante;
    public static javax.swing.JTextField txtNombrePac;
    public static javax.swing.JTextField txtPacAlergias;
    public static javax.swing.JTextField txtPacSintomas;
    public static javax.swing.JTextField txtPresionArtPac;
    public static javax.swing.JTextField txtSatO2Pac;
    public static javax.swing.JTextField txtTemperaturaPac;
    // End of variables declaration//GEN-END:variables
}
