/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.andino.vistas.farmacia;




import ec.com.andino.accesodatos.Conexion;
import ec.com.andino.vistas.frmCambiarClave;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lufeb
 */
public final class frmProducto extends javax.swing.JFrame {
    JLabel img;
    JButton open;
    JFileChooser jf=new JFileChooser();
    FileInputStream fis;
    int longitudBytes;
    TableRowSorter trsFiltro;
    DefaultTableModel modelo;
    public static int codigo;
    public static String nombreFarmaceutico;
    public static String categoria;
    
    /**
     * Creates new form frm
     * @throws java.io.IOException
     * @throws java.sql.SQLException
     */
    public frmProducto() throws IOException, SQLException {
        initComponents();
        consultar_tipoProducto();
        consultar_Proveedor();
        txtCodProducto.setVisible(false);
        txtCodProveedor.setVisible(false);
        txtFarmaceutico.setText(nombreFarmaceutico);
        txtCodFarmacia.setText(String.valueOf(codigo));
        txtCategoria.setText(String.valueOf(categoria));
        setIconImage(new ImageIcon(getClass().getResource("/ec/com/andino/imagenes/icono.png")).getImage());
        setLocationRelativeTo(null);
        this.setDefaultCloseOperation(frmProducto.DO_NOTHING_ON_CLOSE);
        JRootPane boton = SwingUtilities.getRootPane(btnGuardarProducto); 
        boton.setDefaultButton(btnGuardarProducto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel44 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        cmbTipoProducto = new javax.swing.JComboBox<>();
        cmbMedida = new javax.swing.JComboBox<>();
        spinCantidad = new javax.swing.JSpinner();
        spinConcentracion = new javax.swing.JSpinner();
        cmbProveedor = new javax.swing.JComboBox<>();
        txtCodProducto = new javax.swing.JTextField();
        txtCodProveedor = new javax.swing.JTextField();
        spinCostoProveedor = new javax.swing.JSpinner();
        spinValorPvp = new javax.swing.JSpinner();
        txtFarmaceutico = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtCodFarmacia = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        btnGuardarProducto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        BarAcerca = new javax.swing.JMenuItem();
        barManual = new javax.swing.JMenuItem();
        BarCambioClave = new javax.swing.JMenuItem();
        BarSalir = new javax.swing.JMenuItem();

        jLabel44.setText("Bienvenido");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("HE.ANDINO :: Insertar producto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo producto"));

        jLabel2.setText("N. Comerical");

        jLabel6.setText("T.Producto");

        jLabel7.setText("Cantidad");

        jLabel8.setText("Proveedor");

        jLabel9.setText("V.Proveedor");

        jLabel10.setText("pvp");

        jLabel11.setText("Dosificación");

        txtNombreComercial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreComercialFocusLost(evt);
            }
        });

        cmbTipoProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoProductoItemStateChanged(evt);
            }
        });

        cmbMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "mg", "ug", "g", "L", "ml", "cc", "ugotas" }));

        spinCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinConcentracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cmbProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProveedorItemStateChanged(evt);
            }
        });

        txtCodProducto.setEditable(false);

        txtCodProveedor.setEditable(false);

        spinCostoProveedor.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        spinValorPvp.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreComercial)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(spinValorPvp, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spinCostoProveedor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbProveedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbTipoProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(spinConcentracion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(spinCantidad, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCodProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                                .addComponent(txtCodProducto, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinConcentracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(spinCostoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(spinValorPvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtFarmaceutico.setEditable(false);
        txtFarmaceutico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFarmaceutico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Bienvenido");

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("ID");

        txtCodFarmacia.setEditable(false);
        txtCodFarmacia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodFarmacia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/guardar_256px-2.png"))); // NOI18N
        btnGuardarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarProductoMouseEntered(evt);
            }
        });
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/insertar_256px-0.png"))); // NOI18N
        jMenu1.setText("Inicio");

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/receta_256px-0.png"))); // NOI18N
        jMenu4.setText("Receta");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/receta_256px-0.png"))); // NOI18N
        jMenuItem4.setText("Receta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/listar_256px-0.png"))); // NOI18N
        jMenuItem3.setText("Detalle");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/orden_examen_256px-0.png"))); // NOI18N
        jMenu5.setText("Facturación");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/orden_examen_256px-0.png"))); // NOI18N
        jMenuItem2.setText("Factura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/listar_256px-0.png"))); // NOI18N
        jMenuItem5.setText("Detalle");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/editar_256px-0.png"))); // NOI18N
        jMenu2.setText("Modificar");

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/receta_256px-0.png"))); // NOI18N
        jMenu6.setText("Receta");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/receta_256px-0.png"))); // NOI18N
        jMenuItem6.setText("Receta");
        jMenu6.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/listar_256px-0.png"))); // NOI18N
        jMenuItem7.setText("Detalle");
        jMenu6.add(jMenuItem7);

        jMenu2.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/orden_examen_256px-0.png"))); // NOI18N
        jMenu7.setText("Facturación");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/orden_examen_256px-0.png"))); // NOI18N
        jMenuItem8.setText("Factura");
        jMenu7.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/listar_256px-0.png"))); // NOI18N
        jMenuItem9.setText("Detalle");
        jMenu7.add(jMenuItem9);

        jMenu2.add(jMenu7);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/producto.png"))); // NOI18N
        jMenuItem1.setText("Producto");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/ayuda-0.png"))); // NOI18N
        jMenu3.setText("Ayuda");

        BarAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/acerca_de_256px-0.png")));
        BarAcerca.setText("Acerca de ");
        BarAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarAcercaActionPerformed(evt);
            }
        });
        jMenu3.add(BarAcerca);

        barManual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/listar_256px-0.png"))); // NOI18N
        barManual.setText("Manual de Usuario");
        barManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barManualActionPerformed(evt);
            }
        });
        jMenu3.add(barManual);

        BarCambioClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/clave_256px-0.png")));
        BarCambioClave.setText("Cambiar clave");
        BarCambioClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarCambioClaveActionPerformed(evt);
            }
        });
        jMenu3.add(BarCambioClave);

        BarSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/com/andino/imagenes/salir_256px-0.png")));
        BarSalir.setText("Salir");
        BarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarSalirActionPerformed(evt);
            }
        });
        jMenu3.add(BarSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cerrar(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea realmente salir del sistema?",
                "HE.ANDINO", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    public void abrirarchivo(String archivo){
         try {
            File objetofile = new File (archivo);
            Desktop.getDesktop().open(objetofile);
         }catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error "+ex,
                    "HE.ANDINO", JOptionPane.INFORMATION_MESSAGE);
         }
    }
    
    public void consultar_tipoProducto() throws SQLException, IOException{
        Conexion con= new Conexion();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT nombre FROM public.tipoproducto order by nombre asc";
        try {
           pst=con.conectar().prepareStatement(sql);
           rs = pst.executeQuery();
           cmbTipoProducto.addItem("Seleccione");
           while(rs.next()){
               cmbTipoProducto.addItem(rs.getString("nombre"));
           }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos",
                    "HE.ANDINO", JOptionPane.ERROR_MESSAGE);
        }finally{
            con.desconectar();
            rs.close();
        }
    }
    
    public void consultar_Proveedor() throws SQLException, IOException{
        Conexion con= new Conexion();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT nombre FROM public.proveedor order by nombre asc";
        try {
           pst=con.conectar().prepareStatement(sql);
           rs = pst.executeQuery();
           cmbProveedor.addItem("Seleccione");
           while(rs.next()){
               cmbProveedor.addItem(rs.getString("nombre"));
           }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos",
                    "HE.ANDINO", JOptionPane.ERROR_MESSAGE);
        }finally{
            con.desconectar();
            rs.close();
        }
    }
    
    private void btnGuardarProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarProductoMouseEntered
        btnGuardarProducto.setToolTipText("Guardar");
    }//GEN-LAST:event_btnGuardarProductoMouseEntered

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        Conexion con= new Conexion();
        try {
            con.conectar();
        } catch (IOException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (JOptionPane.showConfirmDialog(null, "¿Esta usted seguro?", "HE.ANDINO",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            if(txtNombreComercial.getText().equals("")||spinConcentracion.getValue().equals(0)||txtCodProducto.getText().equals("")
                    ||spinCantidad.getValue().equals(0)||txtCodProveedor.getText().equals("")
                    ||spinCostoProveedor.getValue().equals(0)||spinValorPvp.getValue().equals(0)){
                JOptionPane.showMessageDialog(this, "Debe ingresar toda la información",
                    "HE.ANDINO", JOptionPane.INFORMATION_MESSAGE);
            }else{
                try{
                    String insertarCategoria="INSERT INTO public.producto(\n" +
"	idtipoproducto, idproveedor, nombre, propiedad, pvp, cantidad, costo)\n" +
"	VALUES (?, ?, ?, concat(?, '"+cmbMedida.getSelectedItem()+"'), ?, ?, ?);";
                    try (PreparedStatement ps = con.conectar().prepareStatement(insertarCategoria)) {
                        ps.setInt(1, Integer.parseInt(txtCodProducto.getText()));
                        ps.setInt(2, Integer.parseInt(txtCodProveedor.getText()));
                        ps.setString(3, txtNombreComercial.getText());
                        ps.setString(4, spinConcentracion.getValue().toString());
                        ps.setDouble(5, Double.parseDouble(spinValorPvp.getValue().toString()));
                        ps.setDouble(6, Double.parseDouble(spinCantidad.getValue().toString()));
                        ps.setDouble(7, Double.parseDouble(spinCostoProveedor.getValue().toString()));

                        ps.execute();
                        ps.close();
                    } catch (IOException ex) {
                        Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }catch(SQLException | NumberFormatException | HeadlessException x){
                    JOptionPane.showMessageDialog(rootPane, "Error al guardar la información "+x);
                }finally {
                    con.desconectar();
                }
                txtNombreComercial.setText("");
                spinConcentracion.setValue(0);
                cmbMedida.setSelectedItem("Seleccione");
                cmbTipoProducto.setSelectedItem("Seleccione");
                txtCodProducto.setText("");
                spinCantidad.setValue(0);
                cmbProveedor.setSelectedItem("Seleccione");
                txtCodProveedor.setText("");
                spinCostoProveedor.setValue(0);
                spinValorPvp.setValue(0);
                JOptionPane.showMessageDialog(rootPane,"Guardado correctamente");
            }
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void txtNombreComercialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreComercialFocusLost
        txtNombreComercial.setCaretPosition(0);
    }//GEN-LAST:event_txtNombreComercialFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void BarAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarAcercaActionPerformed
        JOptionPane.showMessageDialog(this, "Sistema médico HE.ANDINO. Versión 2.5\nCopyright (C). 2019. UNACH-NOVENO\n        Todos los Derechos Reservados", "HE.ANDINO",
                JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_BarAcercaActionPerformed

    private void barManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barManualActionPerformed
        abrirarchivo("manual.chm");
    }//GEN-LAST:event_barManualActionPerformed

    private void BarCambioClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarCambioClaveActionPerformed
        JOptionPane.showMessageDialog(this, "Recuerde, el sistema se cerrará \n    luego de cambiar la clave!",
                                "HE.ANDINO", JOptionPane.INFORMATION_MESSAGE);
        frmCambiarClave frm = new frmCambiarClave();
        frm.setVisible(true);
    }//GEN-LAST:event_BarCambioClaveActionPerformed

    private void BarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarSalirActionPerformed
        cerrar();
    }//GEN-LAST:event_BarSalirActionPerformed

    private void cmbTipoProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoProductoItemStateChanged
        Conexion con= new Conexion();
        String tipo = cmbTipoProducto.getSelectedItem().toString();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT idtipoproducto FROM public.tipoproducto where nombre='"+tipo+"'";
        try {
            pst=con.conectar().prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                txtCodProducto.setText(rs.getString("idtipoproducto"));
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos",
                "HE.ANDINO", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbTipoProductoItemStateChanged

    private void cmbProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProveedorItemStateChanged
        Conexion con= new Conexion();
        String tipo = cmbProveedor.getSelectedItem().toString();
        PreparedStatement pst = null;
        ResultSet rs = null;
        String sql = "SELECT idproveedor FROM public.proveedor where nombre='"+tipo+"'";
        try {
            pst=con.conectar().prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                txtCodProveedor.setText(rs.getString("idproveedor"));
            }
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener los datos",
                "HE.ANDINO", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            con.desconectar();
            try {
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(frmProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmbProveedorItemStateChanged

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        frmReceta rec = null;
        try {
            rec = new frmReceta();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmReceta.class.getName()).log(Level.SEVERE, null, ex);
        }
        rec.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        frmRecetaDetalle det = null;
        try {
            det = new frmRecetaDetalle();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmRecetaDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
        det.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmFactura fact = null;
        try {
            fact = new frmFactura();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        fact.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        frmFacturaDetalle detalle = null;
        try {
            detalle = new frmFacturaDetalle();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(frmFacturaDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
        detalle.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BarAcerca;
    private javax.swing.JMenuItem BarCambioClave;
    private javax.swing.JMenuItem BarSalir;
    private javax.swing.JMenuItem barManual;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JComboBox<String> cmbMedida;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JComboBox<String> cmbTipoProducto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinCantidad;
    private javax.swing.JSpinner spinConcentracion;
    private javax.swing.JSpinner spinCostoProveedor;
    private javax.swing.JSpinner spinValorPvp;
    public static javax.swing.JTextField txtCategoria;
    public static javax.swing.JTextField txtCodFarmacia;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtCodProveedor;
    public static javax.swing.JTextField txtFarmaceutico;
    private javax.swing.JTextField txtNombreComercial;
    // End of variables declaration//GEN-END:variables
}
